jmix-framework/jmix

- core/src/main/java/io/jmix/core/common/util/Dom4j.java
See also https://github.com/cuba-platform/cuba/issues/2016
> Provide Dom4j xmlParser with default set of features

- core/src/main/java/io/jmix/core/EntityImportExport.java
- core/src/main/java/io/jmix/core/impl/importexport/EntityImportExportImpl.java
Partial changes for compositions O2M has been implemented
> O2M Composition: Editing nested entities breaks the link with parent entity #107

- core/src/main/java/io/jmix/core/security/event/SingleUserPasswordChangeEvent.java
- core/src/main/java/io/jmix/core/security/event/UserPasswordChangedEvent.java
Also see related changes in security-data: https://github.com/Haulmont/jmix-security/commit/0ff6b3a444c84f3742f99f13844849a2a9042f8b
> Add UserPasswordChangedEvent #215

- core/src/main/java/io/jmix/core/FileClientException.java
- core/src/main/java/io/jmix/core/FileClientManager.java
- core/src/main/java/io/jmix/core/FileClientUtils.java
- core/src/main/java/io/jmix/core/FileInfoResponse.java
- core/src/main/java/io/jmix/core/FileRef.java
- core/src/main/java/io/jmix/core/FileStorageException.java
It is linked with https://github.com/Haulmont/jmix-graphql/pull/187
> Refactoring common part for Rest and Graphql modules

- README.zh-CN.md
Added Chinsese translation of README.md. Gitee will show  README.zh-CN.md  as default project description for China users.
> Add Chinsese translation of README.md

- jmix-ui/ui/src/main/java/io/jmix/ui/model/impl/ScreenDataImpl.java
> Change HashMap to LinkedHashMap in ScreenDataImpl

- jmix-search/search/src/main/java/io/jmix/search/index/queue/impl/JpaIndexingQueueManager.java
> Fix lock\unlock flow in case of concurrent execution of enqueueing session

- jmix-translations/content/io/jmix/dynattrui/messages_el.properties
- jmix-translations/content/io/jmix/emailui/messages_el.properties
- jmix-translations/content/io/jmix/notifications/messages_el.properties
- jmix-translations/content/io/jmix/notificationsui/messages_el.properties
- jmix-translations/content/io/jmix/securityui/messages_el.properties
Add new keys in old files
Add translation for notifications and notificationsui
> Update el translation

- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/dbms/PostgresqlDbmsFeatures.java
Closes issue `Cannot set UUID parameter into native postgres sql query` https://github.com/jmix-framework/jmix/issues/992
> Cannot set UUID parameter into native postgres sql query/jmix#992

- jmix-reports/reports-ui/src/main/java/io/jmix/reportsui/runner/impl/UiReportRunnerImpl.java
> UiReportRunner should not display report parameters window if all parameters are hidden

- jmix-core/core/src/main/java/io/jmix/core/FetchPlanBuilder.java
- jmix-core/core/src/main/java/io/jmix/core/FetchPlans.java
- jmix-core/core/src/main/java/io/jmix/core/FluentLoader.java
- jmix-cuba/cuba/src/main/java/com/haulmont/cuba/core/global/ViewBuilder.java
- jmix-cuba/cuba/src/main/java/com/haulmont/cuba/core/global/ViewBuilderFactory.java
- jmix-graphql/graphql/src/main/java/io/jmix/graphql/datafetcher/DataFetcherPlanBuilder.java
Related forum topic: https://forum.jmix.ru/t/medlennaya-zagruzka-sushhnostej-v-ekranah/734
> Optimization of FetchPlanBuilder creation

- jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/action/ExcelExportAction.java
- jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/action/ExportAction.java
- jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/exporter/AbstractAllRecordsExporter.java
- jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/exporter/excel/ExcelAllRecordsExporter.java
- jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/exporter/excel/ExcelExporter.java
- jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/exporter/json/JsonAllRecordsExporter.java
- jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/exporter/json/JsonExporter.java
- jmix-gridexport/gridexport-ui/src/main/java/io/jmix/gridexportui/action/ExcelExportAction.java
- jmix-gridexport/gridexport-ui/src/main/java/io/jmix/gridexportui/action/ExportAction.java
- jmix-gridexport/gridexport-ui/src/main/java/io/jmix/gridexportui/exporter/AbstractAllRecordsExporter.java
- jmix-gridexport/gridexport-ui/src/main/java/io/jmix/gridexportui/exporter/excel/ExcelAllRecordsExporter.java
- jmix-gridexport/gridexport-ui/src/main/java/io/jmix/gridexportui/exporter/excel/ExcelExporter.java
- jmix-gridexport/gridexport-ui/src/main/java/io/jmix/gridexportui/exporter/json/JsonAllRecordsExporter.java
- jmix-gridexport/gridexport-ui/src/main/java/io/jmix/gridexportui/exporter/json/JsonExporter.java
Linked issue: Add Export All option to JSON export action #1429
> Add Export All option to JSON export action jmix-framework/jmix_1429

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/checkboxgroup/JmixCheckboxGroup.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/AbstractFieldDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/CollectionFieldDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/EntityCollectionFieldDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/multiselectcombobox/JmixMultiSelectComboBox.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/textfield/TypedTextField.java
Fixes jmix-framework/jmix#1456
> The validation message does not disappear after the correct data is entered

- jmix-bom/bom.gradle
Update version of hsqldb driver
> Incorrect conversion of OffsetDateTime values #1009

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/FlowuiProperties.java
- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/LoginViewSupport.java
- jmix-security/security-ui/src/main/java/io/jmix/securityui/authentication/LoginScreenSupport.java
- jmix-ui/ui/src/main/java/io/jmix/ui/UiProperties.java
Fixes: jmix-framework/jmix#1523
> Session fixation protection

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/FlowuiConfiguration.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/JmixTempJarManifestUtils.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/JmixVaadinServletContextInitializer.java
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/module.properties
Fix https://github.com/jmix-framework/jmix/issues/1571
> Long Class-Path may break the frontend #1571

- jmix-bom/bom.gradle
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/JmixEclipseLinkQuery.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/JmixEclipselinkJtaTransactionManager.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/JmixEclipselinkTransactionManager.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/JmixEntityManager.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/JmixEntityManagerFactory.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/JmixPersistenceProvider.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/mapping/JoinCriteriaMappingProcessor.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/mapping/SoftDeleteProcessor.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/support/JmixEclipseLinkJpaVendorAdapter.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/support/JmixIsNullExpressionOperator.java
- jmix-data/eclipselink/src/test/groovy/repository/OrderRepositoryTest.groovy
- jmix-data/eclipselink/src/test/java/test_support/entity/soft_delete/HardDeleteEntity.java
Use fork, adapt to changes from 2 to 4 version
> Upgrade to EclipseLink 4. Part one jmix-framework/jmix#342

- jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/FloatDatatype.java
Fix for release 1.5 (1.6)
Fix for release 2.0 is included into #968
> FloatDatatype doesn't support negative values #1661

- jmix-rest/rest/src/main/java/io/jmix/rest/impl/service/filter/RestFilterParser.java
- jmix-rest/rest/src/main/resources/io/jmix/rest/rest-openapi.yaml
Ported from CUBA: https://github.com/cuba-platform/restapi/commit/12c65740faed20f17705584b2c15d83b78140e7b
> isNull operator in the /entities/search endpoint doesn't work with references jmix-framework/jmix#1699

- jmix-gridexport/gridexport-ui/src/main/java/io/jmix/gridexportui/exporter/excel/AllRecordsExporter.java
Same solution for
1.6.0: https://github.com/jmix-framework/jmix/commit/c408d17ac259177186970df0c9265e6a41d930e6
2.0.0: https://github.com/jmix-framework/jmix/commit/f5158c7b6fdd403b975b1ce6b569a26408d4c41f
> ArrayIndexOutOfBoundsException: on export all rows to Excel with filter conditions on table jmix-framework/jmix#1732

- jmix-core/core/src/main/java/io/jmix/core/CoreProperties.java
- jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/BigDecimalDatatype.java
- jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/DoubleDatatype.java
- jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/FloatDatatype.java
- jmix-core/core/src/test/groovy/datatypes/BigDecimalDatatypeTest.groovy
- jmix-core/core/src/test/groovy/datatypes/DoubleDatatypeTest.groovy
- jmix-core/core/src/test/groovy/datatypes/FloatDatatypeTest.groovy
- jmix-core/core/src/test/groovy/properties/TestCoreProperties.java
- jmix-core/core/src/test/java/test_support/TestCoreProperties.java
https://github.com/jmix-framework/jmix/issues/968
Pay close attention to property - is it ok to put it in 'jmix.core'?
> BigDecimal field values must be rounded according to field format #968

- jmix-quartz/quartz-ui/src/main/java/io/jmix/quartzui/screen/trigger/RepeatMode.java
- jmix-quartz/quartz-ui/src/main/java/io/jmix/quartzui/screen/trigger/TriggerModelEdit.java
- jmix-quartz/quartz-ui/src/main/resources/io/jmix/quartzui/messages.properties
- jmix-quartz/quartz-ui/src/main/resources/io/jmix/quartzui/screen/trigger/trigger-model-edit.xml
- jmix-quartz/quartz/src/main/java/io/jmix/quartz/model/TriggerModel.java
- jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzService.java
- jmix-translations/content/io/jmix/quartzui/messages.properties
- jmix-translations/content/io/jmix/quartzui/messages_ru.properties
> [1.5] Jmix Quartz: Simple Trigger issues

- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/view/roleassignment/RoleAssignmentView.java
- jmix-security/security-flowui/src/main/resources/io/jmix/securityflowui/view/resourcerole/resource-role-model-list-view.xml
- jmix-security/security-flowui/src/main/resources/io/jmix/securityflowui/view/resourcerole/resource-role-model-lookup-view.xml
- jmix-security/security-flowui/src/main/resources/io/jmix/securityflowui/view/roleassignment/role-assignment-view.xml
- jmix-security/security-flowui/src/main/resources/io/jmix/securityflowui/view/rowlevelrole/row-level-role-model-list-view.xml
- jmix-security/security-flowui/src/main/resources/io/jmix/securityflowui/view/rowlevelrole/row-level-role-model-lookup-view.xml
> Role names column is too short in the role assignment screen

- jmix-core/core/src/main/java/io/jmix/core/entity/annotation/CaseConversion.java
The change has been taken from here https://github.com/ikuchmin/jmix/tree/case-conversion-1.4.4
> Allow using CaseConversion in composed annotations (same as BeanValidation annotations)

- jmix-quartz/quartz/src/main/resources/io/jmix/quartz/messages.properties
- jmix-translations/content/io/jmix/quartz/messages.properties
- jmix-translations/content/io/jmix/quartz/messages_ru.properties
> Add localization for Quartz entity names

- jmix-core/core/src/main/java/io/jmix/core/MetadataTools.java
- jmix-core/core/src/test/groovy/metadata/MetadataToolsTest.groovy
> MetadataTools.hasUuid returns false if entity extends MappedSuperclass

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/grid/JmixGrid.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/grid/JmixTreeGrid.java
> partNameGenerator handler created by Studio doesn't work jmix-framework/jmix#2027

- jmix-cuba/cuba/src/main/java/com/haulmont/cuba/settings/converter/LegacyDataGridSettingsConverter.java
- jmix-ui/ui-data/src/test/groovy/uitest/datagrid_settings/DataGridSettingsTest.groovy
- jmix-ui/ui-widgets/src/main/java/io/jmix/ui/widget/client/grid/JmixGridWidget.java
- jmix-ui/ui-widgets/src/main/java/io/jmix/ui/widget/client/treegrid/JmixTreeGridWidget.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/impl/AbstractDataGrid.java
- jmix-ui/ui/src/main/java/io/jmix/ui/model/impl/BaseContainerSorter.java
- jmix-ui/ui/src/main/java/io/jmix/ui/settings/component/DataGridSettings.java
- jmix-ui/ui/src/main/java/io/jmix/ui/settings/component/binder/AbstractDataGridSettingsBinder.java
> Ability to sort by multiple columns in DataGrid jmix-framework/jmix#1265 [1.6.0]

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/impl/DialogsImpl.java
Related to: https://github.com/jmix-framework/jmix/issues/2099
> Increase unsaved changes dialog width

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/component/StudioComponents.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/UiComponentProperties.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/genericfilter/GenericFilter.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/GenericFilterLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/support/ComponentLoaderSupport.java
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/layout.xsd
Related to: #1573
PR only for 2.0 release
> [Filter] Provide the ability to change apply-shortcut

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/DatePickerLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/DateTimePickerLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/support/ComponentLoaderSupport.java
Related to: https://github.com/jmix-framework/jmix/issues/2092
> [DatePicker] support showWeekNumbers in XML jmix-framework/jmix#2092

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/element/StudioElements.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/UiComponentUtils.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/AbstractComboBoxLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/AbstractValuePickerLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/BigDecimalFieldLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/ButtonLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/DatePickerLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/DrawerToggleLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/EmailFieldLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/IntegerFieldLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/NumberFieldLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/PasswordFieldLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/SelectLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/TextAreaLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/TextFieldLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/TimePickerLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/container/TabSheetLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/support/PrefixSuffixLoaderSupport.java
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/layout.xsd
- jmix-flowui/flowui/src/test/groovy/component_xml_load/PrefixSuffixXmlLoadTest.groovy
- jmix-flowui/flowui/src/test/java/component_xml_load/screen/PrefixSuffixView.java
- jmix-flowui/flowui/src/test/resources/component_xml_load/screen/prefix-suffix-view.xml
Studio issue: [JST-4191](https://youtrack.jmix.io/issue/JST-4191/Support-prefixsuffix-elements-in-XML)
Framework issue: jmix-framework/jmix#2096
1. Prefomance issue for: io.jmix.flowui.component.UiComponentUtils#getComponentRecursively
2. Useless DrawerToggle implementation: see issue
> Ability to define prefix and suffix components in XML jmix-framework/jmix#2096

- jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/exporter/excel/ExcelExporter.java
> Entity inspector raise exception on excel export jmix-framework/jmix#2155

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/DetailWindowBuilderProcessor.java
> entity_openComposition action opens an entity editor without current modifications jmix-framework/jmix#2229

- jmix-ui/ui/src/main/java/io/jmix/ui/UiComponentProperties.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/GroupTable.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/impl/GroupTableImpl.java
- jmix-ui/ui/src/main/java/io/jmix/ui/widget/JmixGroupTable.java
- jmix-ui/ui/src/main/java/io/jmix/ui/xml/layout/loader/GroupTableLoader.java
- jmix-ui/ui/src/main/resources/io/jmix/ui/screen/layout.xsd
See https://github.com/jmix-framework/jmix/issues/1242
> Sort by grouping fields when using GroupTable #1242

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/EmailFieldDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/textfield/JmixEmailField.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/validation/RegexpValidator.java
See: #2239
RP for release 2.0 branch: https://github.com/jmix-framework/jmix/pull/2298
> JmixEmailField ignores email pattern jmix-framework/jmix#2239

- jmix-datatools/datatools-flowui/src/main/java/io/jmix/datatoolsflowui/view/entityinspector/EntityInspectorListView.java
See: #2039
Some non-obvious points that appeared due to Vaadin's **UI state update** mechanism are commented in the code.
> Add genericFilter component to EntityInspector jmix-framework/jmix#2039

- jmix-flowui/flowui-themes/src/main/resources/META-INF/resources/themes/jmix-lumo/components/README.md
- jmix-flowui/flowui-themes/src/main/resources/META-INF/resources/themes/jmix-lumo/components/vaadin-form-layout.css
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/model/InstanceLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/model/impl/InstanceLoaderImpl.java
- jmix-templates/content/flowui/master-detail/controller.java
- jmix-templates/content/flowui/master-detail/controller.kt
- jmix-templates/content/flowui/master-detail/descriptor.xml
- jmix-templates/content/flowui/master-detail/settings.xml
See #2249
Merge after: https://github.com/jmix-framework/jmix/pull/2282
> Master-detail view jmix-framework/jmix#2249

- jmix-translations/content/io/jmix/uidata/messages.properties
- jmix-translations/content/io/jmix/uidata/messages_ru.properties
- jmix-ui/ui-data/src/main/java/io/jmix/uidata/action/filter/FilterSaveAsAction.java
- jmix-ui/ui-data/src/main/java/io/jmix/uidata/app/filter/configuration/UiDataFilterConfigurationModelFragment.java
- jmix-ui/ui-data/src/main/java/io/jmix/uidata/filter/FilterConfigurationConverter.java
- jmix-ui/ui-data/src/main/java/io/jmix/uidata/filter/UiDataFilterSupport.java
- jmix-ui/ui-data/src/main/resources/io/jmix/uidata/messages.properties
- jmix-ui/ui/src/main/java/io/jmix/ui/UiComponentProperties.java
- jmix-ui/ui/src/main/java/io/jmix/ui/action/filter/FilterEditAction.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/Filter.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/filter/FilterSupport.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/filter/configuration/DesignTimeConfiguration.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/filter/configuration/RunTimeConfiguration.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/impl/FilterImpl.java
See https://github.com/jmix-framework/jmix/issues/1514
> Prevent from creating filter configurations with the same name #1514

- jmix-flowui/flowui-themes/src/main/resources/META-INF/resources/themes/jmix-lumo/component/jmix-upload-field.css
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/factory/InputDialogGenerationStrategy.java
See https://github.com/jmix-framework/jmix/issues/2273
> InputDialog doesn’t support FileRef #2273

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/StandardDetailView.java
> Don't show save notification in detail view when saved to parent DataContext

- jmix-flowui/flowui-themes/src/main/resources/META-INF/resources/themes/jmix-lumo/component/jmix-upload-field.css
See https://github.com/jmix-framework/jmix/issues/2299
> Label for FileUploadField is not centered in FormLayout #2299

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/ViewControllerDependencyInjector.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/ViewControllerReflectionInspector.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/Subscribe.java
> Support all click events  jmix-framework/jmix#2285

- jmix-flowui/flowui-data/src/main/java/io/jmix/flowuidata/action/genericfilter/AbstractGenericFilterSaveAction.java
- jmix-flowui/flowui-data/src/main/java/io/jmix/flowuidata/component/genericfilter/configuration/UiDataFilterConfigurationDetail.java
- jmix-flowui/flowui-data/src/main/java/io/jmix/flowuidata/genericfilter/GenericFilterConfigurationConverter.java
- jmix-flowui/flowui-data/src/main/java/io/jmix/flowuidata/genericfilter/UiDataGenericFilterSupport.java
- jmix-flowui/flowui-data/src/main/resources/io/jmix/flowuidata/messages.properties
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/UiComponentProperties.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/genericfilter/Configuration.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/genericfilter/GenericFilter.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/genericfilter/GenericFilterSupport.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/genericfilter/configuration/DesignTimeConfiguration.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/genericfilter/configuration/RunTimeConfiguration.java
- jmix-translations/content/io/jmix/flowuidata/messages.properties
- jmix-translations/content/io/jmix/flowuidata/messages_ru.properties
See https://github.com/jmix-framework/jmix/issues/2310
> Prevent from creating filter configurations with the same name (port from 1.6) #2310

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/impl/ActionsImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/AbstractBasePackageConfigurationSorter.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/ActionsConfigurationSorter.java
See https://github.com/jmix-framework/jmix/issues/2344
> Projects ActionsConfiguration must have precedence over addons #2344

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/ViewControllerDependencyInjector.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/ViewControllerReflectionInspector.java
See https://github.com/jmix-framework/jmix/issues/2356
> Incorrect supply target method for setters with same names #2356

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/UiProperties.java
- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/LoginViewSupport.java
See https://github.com/jmix-framework/jmix/issues/2321
> Implement default-view-id application property #2321

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/timer/JmixTimer.java
- jmix-flowui/flowui-kit/src/main/resources/META-INF/frontend/src/timer/jmix-timer.js
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/Timer.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/impl/TimerImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/facet/TimerFacetProvider.java
Moved autostart logic to frontend to get it worked after refresh or duplicate pages
See https://github.com/jmix-framework/jmix/issues/2106
> Implement Timer facet #2106

- jmix-data/data/src/main/java/io/jmix/data/impl/converters/AuditConversionServiceImpl.java
- jmix-data/data/src/main/java/io/jmix/data/impl/converters/AuditConverters.java
- jmix-datatools/datatools/src/main/java/io/jmix/datatools/impl/EntityRestoreImpl.java
See https://github.com/jmix-framework/jmix/issues/2349
> EntityRestore bean assumes that deletedDate attribute has the Date type #2349

- jmix-oidc/oidc-starter/src/main/java/io/jmix/autoconfigure/oidc/OidcAutoConfiguration.java
add CORS support for JWT authenticated API requests
> add CORS support for JWT authenticated API requests

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/DetailWindowBuilderProcessor.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/navigation/DetailViewNavigationProcessor.java
See https://github.com/jmix-framework/jmix/issues/2345
> EditAction must open a view defined by selected entity #2345

- jmix-ui/ui/src/main/java/io/jmix/ui/xml/layout/loader/AbstractTableLoader.java
See https://github.com/jmix-framework/jmix/issues/2367
> Generated column can't be collapsed through XML #2367

- jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/exporter/AbstractDataGridExporter.java
See https://github.com/jmix-framework/jmix/issues/2357
> Excel export fails when column property is not set #2357

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/AbstractNumberFieldDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/IntegerFieldDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/NumberFieldDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/textfield/JmixIntegerField.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/textfield/JmixNumberField.java
See https://github.com/jmix-framework/jmix/issues/2244
> Min and max warning in integer and number fields #2244

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/element/StudioElements.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/AbstractGridDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/TreeGridDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/grid/DataGrid.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/grid/DataGridColumn.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/grid/EnhancedDataGrid.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/grid/TreeDataGrid.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/grid/headerfilter/DataGridHeaderFilter.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/grid/headerfilter/package-info.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/DataGridFilterUrlQueryParametersBinder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/HeaderFilterUrlQueryParametersBinder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/facet/UrlQueryParametersFacetProvider.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/AbstractGridLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/TreeDataGridLoader.java
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/layout.xsd
> Support URL query parameters for the data grid header filter jmix-framework/jmix_2333

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/element/StudioMainViewElements.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/app/main/StandardMainView.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/MainViewLoader.java
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/main/main-view-layout.xsd
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/main/main-view.xsd
- jmix-flowui/flowui/src/test/groovy/main_view/MainViewTest.groovy
- jmix-flowui/flowui/src/test/java/main_view/view/MainView.java
- jmix-flowui/flowui/src/test/java/main_view/view/SandboxView.java
- jmix-flowui/flowui/src/test/resources/main_view/view/main-view.xml
- jmix-flowui/flowui/src/test/resources/main_view/view/sandbox-view.xml
- jmix-templates/content/project/application/src/main/resources/${project_rootPath}/view/main/main-view.xml
See: https://github.com/jmix-framework/jmix/issues/2213
> [MainView] Support for initial layout (2213)

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/event/view/ViewClosedEvent.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/event/view/ViewOpenedEvent.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/DialogWindow.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/View.java
> Implement global view events jmix-framework/jmix#2428

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/menu/MenuConfig.java
- jmix-flowui/flowui/src/test/groovy/menu/MenuConfigMergeTest.groovy
- jmix-flowui/flowui/src/test/groovy/menu/MenuConfigTest.groovy
- jmix-flowui/flowui/src/test/java/component/listmenu/test_support/TestMenuConfig.java
- jmix-flowui/flowui/src/test/resources/menu/menu.xml
- jmix-flowui/flowui/src/test/resources/menu/merge-menu.xml
See https://github.com/jmix-framework/jmix/issues/2347
> Support for menu merging #2347

- jmix-datatools/datatools-ui/src/main/java/io/jmix/datatoolsui/action/ShowEntityInfoAction.java
Ticket - #[1092](https://github.com/jmix-framework/jmix/issues/1092)
>  ShowEntityInfoAction is applicable for several entities

- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/impl/factory/DynAttrComponentGenerationStrategy.java
- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/impl/factory/DynAttrPropertyFilterComponentGenerationStrategy.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/genericfilter/builder/PropertyConditionBuilder.java
Known issue:
https://github.com/jmix-framework/jmix/issues/2535
> Support for dynamic attributes in genericFilter #2343

- jmix-translations/content/io/jmix/ui/messages.properties
- jmix-translations/content/io/jmix/ui/messages_ckb.properties
- jmix-translations/content/io/jmix/ui/messages_de.properties
- jmix-translations/content/io/jmix/ui/messages_el.properties
- jmix-translations/content/io/jmix/ui/messages_fr.properties
- jmix-translations/content/io/jmix/ui/messages_it.properties
- jmix-translations/content/io/jmix/ui/messages_nl.properties
- jmix-translations/content/io/jmix/ui/messages_ro.properties
- jmix-translations/content/io/jmix/ui/messages_ru.properties
- jmix-translations/content/io/jmix/ui/messages_zh_CN.properties
- jmix-ui/ui-themes/src/main/resources/halo/components/fileupload/fileupload.scss
- jmix-ui/ui-widgets/src/main/java/io/jmix/ui/widget/client/jqueryfileupload/JmixFileUploadConnector.java
- jmix-ui/ui-widgets/src/main/java/io/jmix/ui/widget/client/jqueryfileupload/JmixFileUploadProgressWindow.java
- jmix-ui/ui-widgets/src/main/java/io/jmix/ui/widget/client/jqueryfileupload/JmixFileUploadWidget.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/FileMultiUploadField.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/impl/FileMultiUploadFieldImpl.java
- jmix-ui/ui/src/main/java/io/jmix/ui/widget/JmixFileUpload.java
- jmix-ui/ui/src/main/java/io/jmix/ui/widget/client/fileupload/JmixFileUploadState.java
- jmix-ui/ui/src/main/java/io/jmix/ui/xml/layout/loader/FileMultiUploadFieldLoader.java
- jmix-ui/ui/src/main/resources/io/jmix/ui/messages.properties
- jmix-ui/ui/src/main/resources/io/jmix/ui/screen/layout.xsd
See https://github.com/jmix-framework/jmix/issues/2342
> Ability to track progress of FileMultiUploadField upload #2342

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/component/StudioMainViewComponents.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/element/StudioMainViewElements.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/AbstractComponentLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/MainViewLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/support/ComponentLoaderSupport.java
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/main/main-view-layout.xsd
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/main/main-view.xsd
> Components related to main view have no css attribute jmix-framework/jmix#2517

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/genericfilter/GenericFilter.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/logicalfilter/GroupFilter.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/GenericFilterLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/GroupFilterLoader.java
> ResetAction of the GenericFilter breaks the PropertyFilter jmix-framework/jmix#2406

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/component/StudioComponents.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/BaseLoaderConfig.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/AbstractIconLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/FontIconLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/SvgIconLoader.java
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/layout.xsd
- jmix-flowui/flowui/src/test/groovy/component_xml_load/ComponentXmlLoadTest.groovy
- jmix-flowui/flowui/src/test/java/component_xml_load/screen/ComponentView.java
- jmix-flowui/flowui/src/test/resources/component_xml_load/screen/component-view.xml
> Support SvgIcon component jmix-framework/jmix#2414

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/ViewOpeningAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/entitypicker/EntityLookupAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/entitypicker/EntityOpenAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/list/AddAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/list/CreateAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/list/EditAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/list/ReadAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/multivaluepicker/MultiValueSelectAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/ActionViewInitializer.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/AbstractWindowBuilder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/AbstractWindowBuilderProcessor.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/DetailWindowBuilder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/DetailWindowClassBuilder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/DialogWindowBuilder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/LookupWindowBuilder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/LookupWindowClassBuilder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/WindowBuilder.java
> Add setViewConfigurer method to ViewOpeningAction interface jmix-framework/jmix#2507

- jmix-dynattr/dynattr-flowui-kit/src/main/java/io/jmix/dynattrflowui/kit/meta/component/DynAttrStudioComponents.java
- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/panel/DynamicAttributesPanel.java
- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/panel/DynamicAttributesPanelLoader.java
- jmix-dynattr/dynattr-flowui/src/main/resources/io/jmix/dynattrflowui/dynattr.xsd
Removed cols and rows due to FormLayout cannot have columns/rows positions, this props redundant
> fix remove unused tags on dynattr

- jmix-core/core/src/main/java/io/jmix/core/LoadContext.java
- jmix-core/core/src/main/java/io/jmix/core/ValueLoadContext.java
- jmix-core/core/src/main/java/io/jmix/core/querycondition/PropertyCondition.java
- jmix-core/core/src/main/java/io/jmix/core/querycondition/PropertyConditionUtils.java
- jmix-data/data/src/main/java/io/jmix/data/impl/JpqlQueryBuilder.java
- jmix-data/data/src/main/java/io/jmix/data/impl/QueryResultsManagerImpl.java
- jmix-data/data/src/main/java/io/jmix/data/impl/jpql/generator/PropertyConditionGenerator.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/JpaDataStore.java
- jmix-data/eclipselink/src/test/groovy/data_manager/DataManagerPropertyConditionTest.groovy
- jmix-translations/content/io/jmix/ui/messages.properties
- jmix-translations/content/io/jmix/ui/messages_ru.properties
- jmix-ui/ui/src/main/java/io/jmix/ui/component/PropertyFilter.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/factory/PropertyFilterComponentGenerationStrategy.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/filter/FilterMetadataTools.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/propertyfilter/PropertyFilterSupport.java
- jmix-ui/ui/src/main/java/io/jmix/ui/model/impl/CollectionLoaderImpl.java
- jmix-ui/ui/src/main/resources/io/jmix/ui/messages.properties
- jmix-ui/ui/src/main/resources/io/jmix/ui/screen/layout.xsd
See https://github.com/jmix-framework/jmix/issues/518
> Ability to use X-to-many association sub-properties in Filter component #518

- jmix-flowui/flowui-data/src/main/java/io/jmix/flowuidata/action/genericfilter/GenericFilterMakeDefaultAction.java
- jmix-flowui/flowui-data/src/main/java/io/jmix/flowuidata/component/genericfilter/configuration/UiDataFilterConfigurationDetail.java
- jmix-flowui/flowui-data/src/main/java/io/jmix/flowuidata/genericfilter/UiDataGenericFilterSupport.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/action/StudioGenericFilterDataActions.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/settings/component/GenericFilterSettings.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/settings/component/binder/GenericFilterSettingsBinder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/ViewControllerUtils.java
> Implement MakeDefault action for genericFilter component jmix-framework/jmix#1584

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/main/ListMenu.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/menu/ListMenuBuilder.java
See https://github.com/jmix-framework/jmix/issues/2474
> Menu with separator still show even if the menu is not allowed #2474

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/ComponentUtils.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/KeyCombination.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/button/JmixButton.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/button/JmixButtonActionSupport.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/combobutton/ComboButton.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/combobutton/ComboButtonActionSupport.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/delegate/AbstractActionsHolderSupport.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/grid/GridActionsSupport.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/valuepicker/ValuePickerActionSupport.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/valuepicker/ValuePickerButton.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/valuepicker/ValuePickerButtonActionSupport.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/genericfilter/GenericFilterAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/genericfilter/GenericFilter.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/genericfilter/GenericFilterActionsSupport.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/grid/DataGridActionsSupport.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/valuepicker/JmixValuePickerActionSupport.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/impl/ViewActionsImpl.java
See #1758
Changes description: https://github.com/jmix-framework/jmix/issues/1758#issuecomment-1859722867
> Action executed by keyboard shortcut in detail view breaks back navigation

- jmix-core/core/src/main/java/io/jmix/core/LoadContext.java
- jmix-core/core/src/main/java/io/jmix/core/ValueLoadContext.java
- jmix-core/core/src/main/java/io/jmix/core/querycondition/PropertyCondition.java
- jmix-core/core/src/main/java/io/jmix/core/querycondition/PropertyConditionUtils.java
- jmix-data/data/src/main/java/io/jmix/data/impl/JpqlQueryBuilder.java
- jmix-data/data/src/main/java/io/jmix/data/impl/QueryResultsManagerImpl.java
- jmix-data/data/src/main/java/io/jmix/data/impl/jpql/generator/PropertyConditionGenerator.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/JpaDataStore.java
- jmix-data/eclipselink/src/test/groovy/data_manager/DataManagerPropertyConditionTest.groovy
- jmix-translations/content/io/jmix/ui/messages.properties
- jmix-translations/content/io/jmix/ui/messages_ru.properties
- jmix-ui/ui/src/main/java/io/jmix/ui/UiComponentProperties.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/PropertyFilter.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/factory/PropertyFilterComponentGenerationStrategy.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/filter/FilterMetadataTools.java
- jmix-ui/ui/src/main/java/io/jmix/ui/component/propertyfilter/PropertyFilterSupport.java
- jmix-ui/ui/src/main/java/io/jmix/ui/model/impl/CollectionLoaderImpl.java
- jmix-ui/ui/src/main/resources/io/jmix/ui/messages.properties
- jmix-ui/ui/src/main/resources/io/jmix/ui/screen/layout.xsd
See https://github.com/jmix-framework/jmix/issues/2643
> Ability to use X-to-many association sub-properties in Filter component [Port from 1.6] #2643

- jmix-flowui/flowui-starter/src/main/java/io/jmix/autoconfigure/flowui/FlowuiAutoConfiguration.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/UiProperties.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/vaadin/SecurityContextHolderAtmosphereInterceptor.java
See https://github.com/jmix-framework/jmix/issues/2648
> No SecurityContext available when process websocket requests #2648

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/LookupComponent.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/SupportsEnterPress.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/AbstractGridDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/grid/DataGrid.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/grid/DataGridActionsSupport.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/grid/TreeDataGrid.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/StandardListView.java
> Support double click actions in DataGrid (2582)

- jmix-bom/bom.gradle
- jmix-data/data-autoconfigure/src/main/java/io/jmix/autoconfigure/data/JmixLiquibaseCreator.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/JmixEclipselinkJtaTransactionManager.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/JmixEclipselinkTransactionExecutionListener.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/JmixEclipselinkTransactionManager.java
- jmix-email/email/src/main/java/io/jmix/email/impl/EmailerImpl.java
- jmix-flowui/flowui-data/src/main/java/io/jmix/flowuidata/genericfilter/UiDataGenericFilterSupport.java
- jmix-flowui/flowui-data/src/main/java/io/jmix/flowuidata/settings/UserSettingsRemoveUserListener.java
- jmix-flowui/flowui-devserver/flowui-devserver.gradle
- jmix-flowui/flowui-devserver/src/main/java/io/jmix/flowui/devserver/FlowJettyServer.java
- jmix-flowui/flowui-devserver/src/main/java/io/jmix/flowui/devserver/servlet/JmixErrorHandler.java
- jmix-gradle-plugin/build.gradle
- jmix-imap/imap/src/main/java/io/jmix/imap/impl/ImapAttachmentsImpl.java
- jmix-imap/imap/src/main/java/io/jmix/imap/impl/ImapHelper.java
- jmix-imap/imap/src/main/java/io/jmix/imap/impl/ImapManagerImpl.java
- jmix-imap/imap/src/main/java/io/jmix/imap/impl/ImapOperations.java
- jmix-imap/imap/src/main/java/io/jmix/imap/impl/ImapStoreBuilder.java
- jmix-imap/imap/src/main/java/io/jmix/imap/protocol/JmixIMAPProtocol.java
- jmix-imap/imap/src/main/java/io/jmix/imap/protocol/JmixIMAPStore.java
- jmix-imap/imap/src/main/java/io/jmix/imap/protocol/ThreadExtension.java
- jmix-imap/imap/src/main/java/io/jmix/imap/sync/ImapFlaglessSynchronizer.java
- jmix-imap/imap/src/main/java/io/jmix/imap/sync/ImapSynchronizer.java
- jmix-security/security-data/src/main/java/io/jmix/securitydata/impl/SubstitutionUserRemovalHandler.java
- jmix-security/security-data/src/main/java/io/jmix/securitydata/impl/role/assignment/RoleAssignmentUserRemovalHandler.java
> Upgrade to Spring Boot 3.2 (#2503)

- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/dbms/SqlServerDbmsFeatures.java
> fix Unique constraint violation is not handled correctly when using Iatest MS SQLServer

- jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzService.java
https://github.com/jmix-framework/jmix/issues/2743
> transactional quartz job update 2743

- jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/QuartzExceptionHandler.java
- jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/QuartzFlowUIExceptionHandler.java
- jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/view/jobs/JobModelDetailView.java
- jmix-quartz/quartz-flowui/src/main/resources/io/jmix/quartzflowui/messages.properties
- jmix-quartz/quartz/src/main/java/io/jmix/quartz/exception/QuartzJobSaveException.java
- jmix-quartz/quartz/src/main/java/io/jmix/quartz/model/JobModel.java
- jmix-quartz/quartz/src/main/java/io/jmix/quartz/model/TriggerModel.java
- jmix-quartz/quartz/src/main/java/io/jmix/quartz/service/QuartzService.java
https://github.com/jmix-framework/jmix/issues/2595
> added exception handling for quartz ui and validations for models 2595

- jmix-datatools/datatools-flowui/src/main/java/io/jmix/datatoolsflowui/view/entityinspector/EntityInspectorDetailView.java
See https://github.com/jmix-framework/jmix/issues/2723
> Bug in Entity inspector when opening entity with ManyToMany relation #2723

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/AbstractGridDelegate.java
See https://github.com/jmix-framework/jmix/issues/2221
> Grid selection with versioned Entity #2221

- jmix-datatools/datatools-flowui/src/main/java/io/jmix/datatoolsflowui/view/entityinspector/EntityInspectorListView.java
See https://github.com/jmix-framework/jmix/issues/2734
> Exception in Entity Inspector Selection because of DummyAppSettingsEntity #2734

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/ViewControllerDependencyInjector.java
> Implement event subscription support for child components for dropdownButton items jmix-framework/jmix#2621

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/ComponentUtils.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/KeyCombination.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/delegate/AbstractActionsHolderSupport.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/binder/AbstractShortcutActionBindingImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/view/DetailCloseAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/view/DetailSaveAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/view/DetailSaveCloseAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/view/ViewCloseAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/impl/ViewActionsImpl.java
> Support resetFocusOnActiveElement for actions jmix-framework/jmix#2626

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/component/StudioHTMLComponents.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/BaseLoaderConfig.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/html/NativeDetailsLoader.java
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/layout.xsd
- jmix-flowui/flowui/src/test/groovy/component_xml_load/HtmlComponentXmlLoadTest.groovy
- jmix-flowui/flowui/src/test/java/component_xml_load/screen/HtmlView.java
- jmix-flowui/flowui/src/test/resources/component_xml_load/screen/html-view.xml
> Support nativeDetails component jmix-framework/jmix#2771

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/DateInternationalizationHelper.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/datepicker/TypedDatePicker.java
- jmix-flowui/flowui/src/test/groovy/date_internationalization/DateInternationalizationHelperTest.groovy
See https://github.com/jmix-framework/jmix/issues/2795 for details
> Mapping from Calendar to Vaadin dayOfWeek

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/component/StudioComponents.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/element/StudioElements.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/LoginOverlayLoader.java
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/layout.xsd
> Support LoginOverlay component in Studio meta jmix-framework/jmix#2794

- jmix-email/email-flowui/src/main/resources/io/jmix/emailflowui/messages.properties
- jmix-email/email-flowui/src/main/resources/io/jmix/emailflowui/view/sendingmessage/sending-message-view.xml
- jmix-translations/content/io/jmix/emailflowui/messages.properties
- jmix-translations/content/io/jmix/emailflowui/messages_ru.properties
#1763
According to the issue we cannot change column width. But in the current version we able to change column width and order.
As small improvement I added settings facet to save user preferences for the dataGrid.
> Email history table content isn't fully visible 1763

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/filedownloader/JmixFileDownloader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/download/DownloaderImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/download/FileNotExistsExceptionHandler.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/exception/FileNotExistsExceptionHandler.java
#2809
UI notification shows when FileStorageException occures
> Downloader bean doesn't check if file exists 2809

- jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/exporter/excel/ExcelExporter.java
- jmix-gridexport/gridexport-ui/src/main/java/io/jmix/gridexportui/exporter/excel/ExcelExporter.java
> Excel export throws exception for the float data type 2706

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/ViewOpeningAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/entitypicker/EntityLookupAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/entitypicker/EntityOpenAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/impl/ActionHandlerValidator.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/impl/package-info.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/list/AddAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/list/CreateAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/list/EditAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/list/ReadAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/multivaluepicker/MultiValueSelectAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/ActionViewInitializer.java
> Show warning in the log at runtime if action has inappropriate handlers for the open mode

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/ComponentUtils.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/button/JmixButtonActionSupport.java
- jmix-flowui/flowui/src/test/groovy/component/button/JmixButtonTest.groovy
> Incorrect assignment of action icon to jmix button 2779

- jmix-ui/ui/src/main/java/io/jmix/ui/sys/UiControllerDependencyInjector.java
- jmix-ui/ui/src/test/groovy/ui_controller_dependency_injector/UiControllerDependencyInjectorTest.groovy
- jmix-ui/ui/src/test/java/test_support/UiTestConfiguration.java
- jmix-ui/ui/src/test/java/ui_controller_dependency_injector/screen/ValueAnnotationTestScreen.java
- jmix-ui/ui/src/test/resources/test_support/test-ui-app.properties
- jmix-ui/ui/src/test/resources/ui_controller_dependency_injector/screen/value-annotation-test-screen.xml
#2713
Now supports any types for fields with the value annotation (Integer, Double etc)
> Value annotation in screen controllers supports only string 2713

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/model/DataLoader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/model/ViewData.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/model/impl/CollectionLoaderImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/model/impl/InstanceLoaderImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/model/impl/KeyValueCollectionLoaderImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/model/impl/KeyValueInstanceLoaderImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/model/impl/ViewDataImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/monitoring/DataLoaderLifeCycle.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/monitoring/DataLoaderMonitoringInfo.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/monitoring/UiMonitoring.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/monitoring/ViewLifeCycle.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/monitoring/package-info.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/ViewSupport.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/View.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/ViewControllerUtils.java
[#1704](https://github.com/jmix-framework/jmix/issues/1704)
> Monitoring loader in screens 1704

- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/impl/factory/DynAttrComponentGenerationStrategy.java
- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/view/categoryattr/CategoryAttributesDetailView.java
- jmix-dynattr/dynattr/src/main/java/io/jmix/dynattr/utils/DynAttrStringUtils.java
- jmix-dynattr/dynattr/src/test/groovy/dynamic_attributes/DynAttrStringUtilsTest.groovy
- jmix-translations/content/io/jmix/dynattrflowui/messages_ru.properties
> Change logics for code generation for code attributes #2570

- jmix-dynattr/dynattr-flowui-kit/src/main/java/io/jmix/dynattrflowui/kit/meta/component/DynAttrStudioComponents.java
- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/impl/BaseEmbeddingStrategy.java
- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/panel/DynamicAttributesPanel.java
- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/panel/DynamicAttributesPanelLoader.java
- jmix-dynattr/dynattr-flowui/src/main/resources/io/jmix/dynattrflowui/dynattr.xsd
I replace https://github.com/jmix-framework/jmix/pull/2869 with this PR
> add property "category field visibility" on the dynamic attribute panel #2737

- jmix-flowui/flowui-themes/src/main/resources/META-INF/resources/themes/jmix-lumo/app/main-view-top-menu.css
> Align icon in main view

- jmix-flowui/flowui-kit/src/main/resources/META-INF/frontend/src/value-picker/jmix-value-picker.js
> Allow custom validation work with required for value picker components 2856

- jmix-templates/content/project/application-kotlin/src/main/resources/${project_rootPath}/view/user/user-detail-view.xml
- jmix-templates/content/project/application/src/main/resources/${project_rootPath}/view/user/user-detail-view.xml
> Add clear button for timeZoneField 1218

- jmix-jmxconsole/jmxconsole/src/main/java/io/jmix/jmxconsole/view/MBeanOperationResultView.java
> Change the colon to a dash in the file name 2816

- jmix-ui/ui/src/main/java/io/jmix/ui/component/formatter/Formatter.java
> Add @Nullable annotation to Formatter#apply 1393

- jmix-ui/ui/src/main/java/io/jmix/ui/component/mainwindow/impl/UserIndicatorImpl.java
> Reload user in UserIndicator when refresh method call 2456

- jmix-ui/ui/src/main/java/io/jmix/ui/sys/ScreensImpl.java
> Add cause of exception if screen controller cannot be created 2700

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/AbstractTextInputFieldDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/AbstractValueComponentDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/DatePickerDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/DateTimePickerDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/TextAreaFieldDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/TimePickerDelegate.java
- jmix-flowui/flowui/src/test/groovy/component/delegate/AbstractValueComponentDelegateTest.groovy
> Change AbstractValueComponentDelegate.setupProperties param type to ValueSource

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/codeeditor/JmixCodeEditor.java
- jmix-flowui/flowui-kit/src/main/resources/META-INF/frontend/src/code-editor/jmix-code-editor.js
> Set focus to internal text area manually 2930

- jmix-bom/bom.gradle
Add AzureFS and AzureFS starter dependencies to bom.gradle
>  Add AzureFS addon for jmix version 2.2.x 

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/codeeditor/JmixCodeEditor.java
- jmix-flowui/flowui-kit/src/main/resources/META-INF/frontend/src/code-editor/jmix-code-editor.js
> Remove extra click in BPM script editor

- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/FlowuiSecurityConfiguration.java
- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/util/PrevVaadinRequestUtil.java
> Anonymous view access stopped working

- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/view/category/CategoryDetailView.java
> Remove callback data provider 2833

- jmix-data/data/src/main/java/io/jmix/data/impl/dbms/HsqlSequenceSupport.java
- jmix-data/eclipselink/src/test/groovy/number_id_generation/NumberIdConcurrencyTest.groovy
> Change hsql script for sequence current value 2180

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/settings/component/binder/AbstractGridSettingsBinder.java
> Reset column flexGrow before set width in settings 2965

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/menu/ListMenuBuilder.java
- jmix-flowui/flowui/src/test/groovy/component/listmenu/ListMenuTest.groovy
> Replace dash with underscore to match with enum value 2917

- jmix-ui/ui/src/main/java/io/jmix/ui/component/factory/JpqlFilterComponentGenerationStrategy.java
> Changing the way of creation of an entityPicker 2516

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/main/JmixUserIndicator.java
- jmix-flowui/flowui/src/test/groovy/test_support/spec/FlowuiTestSpecification.groovy
> Refresh authenticated user in JmixUserIndicator 2918

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/component/GridColumnVisibilityLoader.java
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/layout.xsd
> Use loadResourceString instead of loadString

- jmix-templates/content/flowui/main-view-top-menu/descriptor.xml
- jmix-templates/content/flowui/main-view-top-menu/settings.xml
> Change plain strings to messages

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/UiComponentUtils.java
- jmix-flowui/flowui/src/test/groovy/dependency_injector/ViewControllerDependencyInjectorTest.groovy
- jmix-flowui/flowui/src/test/java/dependency_injector/view/DependencyInjectorView.java
- jmix-flowui/flowui/src/test/resources/dependency_injector/view/dependency-injector-view.xml
> Consider the component path in getComponentRecursively

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/UiEventPublisher.java
> Publish event to all user sessions instead of only for current session

- jmix-translations/content/io/jmix/notificationsflowui/messages.properties
- jmix-translations/content/io/jmix/notificationsflowui/messages_de.properties
- jmix-translations/content/io/jmix/notificationsflowui/messages_el.properties
- jmix-translations/content/io/jmix/notificationsflowui/messages_es.properties
- jmix-translations/content/io/jmix/notificationsflowui/messages_ru.properties
https://github.com/jmix-framework/jmix/issues/2961
> Missing messages in Notification add-on RU translation 2961

- jmix-authserver/authserver-starter/src/main/java/io/jmix/autoconfigure/authserver/AuthServerAutoConfiguration.java
- jmix-authserver/authserver/src/main/java/io/jmix/authserver/authentication/OAuth2ResourceOwnerPasswordCredentialsAuthenticationConverter.java
- jmix-authserver/authserver/src/main/java/io/jmix/authserver/authentication/OAuth2ResourceOwnerPasswordCredentialsAuthenticationProvider.java
- jmix-authserver/authserver/src/main/java/io/jmix/authserver/authentication/OAuth2ResourceOwnerPasswordCredentialsAuthenticationToken.java
- jmix-authserver/authserver/src/main/java/io/jmix/authserver/authentication/OAuth2ResourceOwnerPasswordTokenEndpointConfigurer.java
- jmix-authserver/authserver/src/main/java/io/jmix/authserver/introspection/AuthorizationServiceOpaqueTokenIntrospector.java
> Resource owner password credentials grant

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/gridcolumnvisibility/JmixGridColumnVisibility.java
- jmix-flowui/flowui/src/test/groovy/component_xml_load/GridColumnVisibilityXmlLoadTest.groovy
- jmix-flowui/flowui/src/test/resources/component_xml_load/screen/grid-column-visibility-view.xml
- jmix-flowui/flowui/src/test/resources/test_support/messages.properties
> Get column header text from filter header internal component 2960

- jmix-templates/content/flowui/master-detail/controller.java
- jmix-templates/content/flowui/master-detail/controller.kt
> No form validation inside MasterDetailView 2959

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/list/EditAction.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/action/list/ReadAction.java
- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/action/AssignToUsersAction.java
- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/action/ShowRoleAssignmentsAction.java
- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/action/ShowUserSubstitutionsAction.java
> Disable Edit button in multi select Grid 889

- jmix-templates/content/flowui/master-detail/descriptor.xml
> Add id for master-detail form inside master-detail-view studio template 2958

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/Dialogs.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/impl/DialogsImpl.java
> Ability to display HTML content in background task dialog 3054

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/GenericFilterUrlQueryParametersBinder.java
> GenericFilter creates filter conditions for System level attributes or excluded attributes added through URL query parameters 3016

- jmix-reports/reports/src/main/java/io/jmix/reports/libintegration/JmixDocxFormatter.java
- jmix-reports/reports/src/main/java/io/jmix/reports/libintegration/JmixFormatterFactory.java
https://github.com/jmix-framework/jmix/issues/3122
> NPE when generating a DOCX report with a formatter 3122

- jmix-reports/reports-flowui/src/main/java/io/jmix/reportsflowui/view/report/ReportListView.java
- jmix-reports/reports-flowui/src/main/resources/io/jmix/reportsflowui/view/report/report-list-view.xml
https://github.com/jmix-framework/jmix/issues/3089
> Reports not sortable by name 3089

- jmix-ui/ui/src/main/java/io/jmix/ui/component/impl/AbstractTable.java
> Exception if a user has no permission to a column that is collapsed via XML jmix-framework/jmix#3110

- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/JpaDataStore.java
> Localization does not apply to unique constraints in MSSQL 3030

- jmix-reports/reports-flowui/src/main/java/io/jmix/reportsflowui/view/template/ReportTemplateDetailView.java
[3185](https://github.com/jmix-framework/jmix/issues/3185)
> Report Templates CodeEditor Fullscreen link should not be shown without editor 3185

- jmix-audit/audit-flowui/src/main/java/io/jmix/auditflowui/view/entitylog/EntityLogView.java
https://github.com/jmix-framework/jmix/issues/3034
> Use fetch callback to load users while searching in EntityLogView 3034

- jmix-templates/content/project/application-kotlin/src/main/kotlin/${project_rootPath}/security/${project_classPrefix}SecurityConfiguration.kt
- jmix-templates/content/project/application/src/main/java/${project_rootPath}/security/${project_classPrefix}SecurityConfiguration.java
> Spring Security configuration class in a project template

- jmix-appsettings/appsettings/src/main/java/io/jmix/appsettings/impl/AppSettingsToolsImpl.java
- jmix-core/core/src/main/java/io/jmix/core/common/util/ReflectionHelper.java
- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/lazyloading/ValueHoldersSupport.java
Cache fields for #1247 at release 1.6
Next step is to cache annotated methods
> Fields cache to 1.6 #1247

- jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/event/JobExecutionListener.java
- jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/view/jobs/JobModelDetailView.java
- jmix-quartz/quartz-flowui/src/main/java/io/jmix/quartzflowui/view/jobs/JobModelListView.java
- jmix-quartz/quartz-flowui/src/main/resources/io/jmix/quartzflowui/view/jobs/job-model-list-view.xml
https://github.com/jmix-framework/jmix/issues/3281
> Rework job statuses acquiring

- jmix-core/core/src/main/java/io/jmix/core/impl/repository/support/JmixDataRepositoryImpl.java
- jmix-core/core/src/main/java/io/jmix/core/repository/JmixDataRepository.java
- jmix-core/core/src/main/java/io/jmix/core/repository/JmixDataRepositoryUtils.java
- jmix-templates/content/flowui/detail/controller.java
- jmix-templates/content/flowui/detail/controller.kt
- jmix-templates/content/flowui/detail/descriptor.xml
- jmix-templates/content/flowui/detail/settings.xml
- jmix-templates/content/flowui/list-and-detail/settings.xml
- jmix-templates/content/flowui/list/controller.java
- jmix-templates/content/flowui/list/controller.kt
- jmix-templates/content/flowui/list/descriptor.xml
- jmix-templates/content/flowui/list/settings.xml
- jmix-templates/content/flowui/master-detail/controller.java
- jmix-templates/content/flowui/master-detail/controller.kt
- jmix-templates/content/flowui/master-detail/descriptor.xml
- jmix-templates/content/flowui/master-detail/settings.xml
@knstvk, @gorbunkov could you please check api, messages and javadocs?
@tmusin could you please check templates? maybe the part that generates warning message should be moved to groovy script?
> Jmix Data Repositories in Views. Templates, helper class jmix-framework/jmix#2881

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/component/StudioComponents.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/component/StudioMainViewComponents.java
> Fix default value of listMenu.loadMenuConfig attribute shown in studio inspector

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/main/ListMenu.java
> MenuBarItem does not attach child item to a menu

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/download/Downloader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/download/DownloaderImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/download/FileRefDownloadDataProvider.java
> Downloader file existence check is not correct

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/main/ListMenu.java
> Add listener to MenuBarItem to handle open state changes

- jmix-flowui/flowui-test-assist/src/main/java/io/jmix/flowui/testassist/JmixUiTestExtension.java
- jmix-flowui/flowui-test-assist/src/main/java/io/jmix/flowui/testassist/navigation/TestDetailViewNavigationProcessor.java
- jmix-flowui/flowui-test-assist/src/main/java/io/jmix/flowui/testassist/navigation/TestListViewNavigationProcessor.java
- jmix-flowui/flowui-test-assist/src/main/java/io/jmix/flowui/testassist/navigation/TestViewNavigationProcessor.java
- jmix-flowui/flowui-test-assist/src/main/java/io/jmix/flowui/testassist/navigation/ViewNavigationDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/navigation/AbstractNavigationProcessor.java
Fixes for: https://github.com/jmix-framework/jmix/issues/2219
> Support DefaultMainViewParent in Test Assist (2219)

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/UiComponentProperties.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/factory/EntityFieldCreationSupport.java
- jmix-flowui/flowui/src/test/groovy/generation_strategy/EntityFieldPropertiesTest.groovy
- jmix-flowui/flowui/src/test/groovy/generation_strategy/GenerationStrategyTest.groovy
- jmix-flowui/flowui/src/test/resources/test_support/test-flowui-app.properties
> Support entityFieldFqn and entityFieldActions application properties jmix-framework/jmix#3331

- jmix-security/security/src/main/java/io/jmix/security/configurer/AuthorizedApiUrlsConfigurer.java
> AuthorizedApiUrlsConfigurer should create AntPathRequestMatchers

- jmix-authserver/authserver-starter/src/main/java/io/jmix/autoconfigure/authserver/AuthServerAutoConfiguration.java
- jmix-oidc/oidc-starter/src/main/java/io/jmix/autoconfigure/oidc/OidcAutoConfiguration.java
- jmix-oidc/oidc/src/main/java/io/jmix/oidc/OidcVaadinWebSecurity.java
- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/security/FlowuiVaadinWebSecurity.java
- jmix-security/security/src/main/java/io/jmix/security/SecurityConfigurers.java
- jmix-security/security/src/main/java/io/jmix/security/configurer/AnonymousConfigurer.java
- jmix-security/security/src/main/java/io/jmix/security/configurer/AuthorizedApiUrlsConfigurer.java
- jmix-security/security/src/main/java/io/jmix/security/configurer/CompositeConfigurer.java
- jmix-security/security/src/main/java/io/jmix/security/configurer/DefaultConfigurer.java
- jmix-security/security/src/main/java/io/jmix/security/configurer/RememberMeConfigurer.java
- jmix-security/security/src/main/java/io/jmix/security/configurer/SessionManagementConfigurer.java
- jmix-security/security/src/main/java/io/jmix/security/configurer/StandardSecurityConfigurer.java
- jmix-security/security/src/main/java/io/jmix/security/util/JmixHttpSecurityUtils.java
See #3391 
Jmix security configurers were marked deprecated;
Jmix security configurers invocations were replaced by JmixHttpSecurityUtils;
> JmixHttpSecurityUtils

- jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/exporter/entitiesloader/AbstractAllEntitiesLoader.java
- jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/exporter/entitiesloader/KeysetAllEntitiesLoader.java
- jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/exporter/entitiesloader/LimitOffsetAllEntitiesLoader.java
> Use load data with delegate if exists 3313

- jmix-reports/reports/src/main/java/io/jmix/reports/yarg/formatters/impl/jasper/JRBandDataDataSource.java
> Fix #3393 JRBandDataDataSource next method null pointer exception

- jmix-cuba/cuba/src/main/java/com/haulmont/cuba/gui/components/filter/FilterDelegateImpl.java
> Support Jmix tables within AppFolder - Sets

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/data/binding/HtmlContainerReadonlyDataBinding.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/data/binding/impl/HtmlContainerReadonlyDataBindingImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/html/AbstractHtmlContainerLoader.java
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/layout.xsd
- jmix-flowui/flowui/src/test/groovy/component_xml_load/HtmlComponentXmlLoadTest.groovy
- jmix-flowui/flowui/src/test/groovy/data_binding_html_container/HtmlContainerReadonlyDataBindingTest.groovy
- jmix-flowui/flowui/src/test/java/data_binding_html_container/view/DataBindingHtmlContainerView.java
- jmix-flowui/flowui/src/test/java/test_support/entity/Zoo.java
- jmix-flowui/flowui/src/test/resources/data_binding_html_container/view/data-binding-html-container-view.xml
> Data binding for HTML components 3288

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/container/TabSheetLoader.java
> Bind button and grid action when lazy tab is opened 3423

- jmix-core/core/src/main/java/io/jmix/core/impl/MetaModelLoader.java
- jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/AdaptiveNumberDatatype.java
- jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/NumberDatatype.java
- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/impl/factory/DynAttrComponentGenerationStrategy.java
- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/view/categoryattr/CategoryAttributesDetailView.java
> Exception in case of wrong value in a field with the NumberFormat annotation 3512

- jmix-core/core/src/main/resources/io/jmix/core/messages.properties
- jmix-translations/content/io/jmix/core/messages.properties
- jmix-translations/content/io/jmix/core/messages_ru.properties
> There is no messages for date constraints validation

- jmix-templates/content/flowui/list-dto/controller.java
- jmix-templates/content/flowui/list-dto/controller.kt
> Illegal argument exception when using dto entity list view template without remove action

- jmix-appsettings/appsettings-flowui/src/main/java/io/jmix/appsettingsflowui/view/appsettings/AppSettingsEntityView.java
> It is impossible to copy default value of the application settings

- jmix-templates/content/flowui/master-detail/controller.java
- jmix-templates/content/flowui/master-detail/controller.kt
> Action aware view generation 3245

- jmix-reports/reports/src/main/java/io/jmix/reports/libintegration/JmixHtmlFormatter.java
- jmix-reports/reports/src/main/java/io/jmix/reports/yarg/formatters/impl/AbstractFormatter.java
- jmix-reports/reports/src/main/java/io/jmix/reports/yarg/formatters/impl/XlsxFormatter.java
https://github.com/jmix-framework/jmix/issues/3159
> Support for value formats in HTML-reports 3159

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/impl/UrlQueryParametersFacetImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/navigation/RouteSupport.java
> Problem with URL changing in browser address bar when using urlQueryParameters in the menu

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/StandardDetailView.java
See #3533
Policy is a DTO and doesn't have fetch plan - there should be no check for `.isLoadedWithFetchPlan` in this case
> IllegalArgumentException while editing a policy in the resource role editor

- jmix-datatools/datatools-flowui/src/main/java/io/jmix/datatoolsflowui/view/entityinspector/EntityInspectorDetailView.java
- jmix-datatools/datatools-flowui/src/main/java/io/jmix/datatoolsflowui/view/entityinspector/assistant/InspectorFormLayoutBuilder.java
> IllegalStateException: Current item is null while edit category attribute via entity inspector #3107

- jmix-audit/audit-flowui/src/main/java/io/jmix/auditflowui/view/entitylog/EntityLogView.java
- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/view/category/CategoryDetailView.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/autowire/AutowireUtils.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/autowire/ReflectionCacheManager.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/autowire/SelectionListenerDependencyInjector.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/autowire/ViewSubscribeDependencyInjector.java
- jmix-reports/reports-flowui/src/main/java/io/jmix/reportsflowui/view/reportwizard/ReportWizardCreatorView.java
See: #3552
Related Jmix Studio issue: [JST-5239](https://youtrack.jmix.io/issue/JST-5239/Support-declarative-subscription-for-SelectionListener)
> Support DataGrid SelectionEvent with Subscribe annotation

- jmix-bom/bom.gradle
- jmix-gradle-plugin/build.gradle
- jmix-templates/content/project/application-kotlin/build.gradle
- jmix-templates/content/project/application-kotlin/gradle.properties
- jmix-templates/content/project/application/build.gradle
- jmix-templates/content/project/application/gradle.properties
See: #3459
Source of information: https://vaadin.com/docs/latest/upgrading#hilla-react-dependencies
Studio issue will be created after review
> Exclude Hilla dependencies in project template #3459

- jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/DatatypeFormatter.java
Updated signature of DatatypeFormatter parse method to accept null strings.
See: #3666
> Updated signature of DatatypeFormatter parse method to accept null srings

- jmix-dynattr/dynattr-flowui/src/main/resources/io/jmix/dynattrflowui/view/category/category-list-view.xml
Remove margin in cattributesBox, see #3618
>  3618 fix visual bug in CattegoryListView

- jmix-search/search/src/main/java/io/jmix/search/utils/FileProcessor.java
> Search displays some meta information of indexed xlsx file

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/component/StudioComponents.java
> Remove the metaClass attribute from the listMenu component 3675

- jmix-audit/audit-ui/src/main/resources/io/jmix/auditui/screen/sessions/user-sessions-browse.xml
> When opening User session screen, the list of sessions is empty 3514

- jmix-search/search/src/main/java/io/jmix/search/utils/FileProcessor.java
> Search doesn't support parsing of the files which extensions are written with capital case letters #3696

- jmix-charts/charts-flowui/src/main/java/io/jmix/chartsflowui/component/serialization/AbstractDataSerializer.java
> Date datatype can't be formatted for Axes 3620

- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/model/RoleModelConverter.java
- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/view/resourcerole/ResourceRoleModelDetailView.java
> Add default sorting to Policy group column in Resource role window 3360

- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/panel/DynamicAttributesPanel.java
- jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/panel/package-info.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/UiComponentUtils.java
- jmix-templates/content/flowui/master-detail/controller.java
- jmix-templates/content/flowui/master-detail/controller.kt
> The fields of dynamic attributes are available for modification before the entity editing is started 3181

- jmix-multitenancy/multitenancy-flowui/src/test/java/test_support/entity/User.java
- jmix-multitenancy/multitenancy/src/main/java/io/jmix/multitenancy/core/AcceptsTenant.java
- jmix-multitenancy/multitenancy/src/main/java/io/jmix/multitenancy/core/impl/TenantProviderImpl.java
> Get rid of AcceptsTenant interface jmix-framework/jmix#2404

- jmix-core/core/src/main/java/io/jmix/core/HasTimeZone.java
- jmix-core/core/src/main/java/io/jmix/core/security/DeviceTimeZoneProvider.java
- jmix-core/core/src/main/java/io/jmix/core/security/impl/CurrentAuthenticationImpl.java
- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/LoginViewSupport.java
- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/security/DeviceTimeZoneProviderImpl.java
- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/security/package-info.java
- jmix-templates/content/project/application-kotlin/src/main/kotlin/${project_rootPath}/entity/User.kt
- jmix-templates/content/project/application/src/main/java/${project_rootPath}/entity/User.java
> Use browser timezone if user timezone is not set jmix-framework/jmix#3551

- jmix-pessimisticlock/pessimisticlock/src/main/java/io/jmix/pessimisticlock/impl/LockManagerImpl.java
> LockManager lock should work atomically

- jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/ElasticsearchIndexSettingsProvider.java
- jmix-search/search-opensearch/src/main/java/io/jmix/searchopensearch/index/OpenSearchIndexSettingsProvider.java
> Index settings are not generated properly(correction)

- jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/ElasticsearchIndexSettingsProvider.java
- jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/searching/strategy/impl/AllTermsAnyFieldElasticsearchSearchStrategy.java
- jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/searching/strategy/impl/AllTermsSingleFieldElasticsearchSearchStrategy.java
- jmix-search/search-flowui-kit/src/main/java/io/jmix/searchflowui/kit/meta/component/StudioSearchComponents.java
- jmix-search/search-flowui/src/main/java/io/jmix/searchflowui/loader/SearchFieldLoader.java
- jmix-search/search-flowui/src/main/java/io/jmix/searchflowui/view/settings/SearchFieldSettingsView.java
- jmix-search/search-flowui/src/main/resources/io/jmix/searchflowui/messages.properties
- jmix-search/search-opensearch/src/main/java/io/jmix/searchopensearch/index/OpenSearchIndexSettingsProvider.java
- jmix-search/search-opensearch/src/main/java/io/jmix/searchopensearch/searching/impl/OpenSearchEntitySearcher.java
- jmix-search/search-opensearch/src/main/java/io/jmix/searchopensearch/searching/strategy/impl/AllTermsAnyFieldOpenSearchSearchStrategy.java
- jmix-search/search-opensearch/src/main/java/io/jmix/searchopensearch/searching/strategy/impl/AllTermsSingleFieldOpenSearchSearchStrategy.java
- jmix-search/search/src/main/java/io/jmix/search/SearchProperties.java
- jmix-search/search/src/main/java/io/jmix/search/index/BaseIndexSettingsConfigurationContext.java
- jmix-translations/content/io/jmix/searchflowui/messages.properties
- jmix-translations/content/io/jmix/searchflowui/messages_ru.properties
- Revert breaking changes.
- Fix localization
- Output search request
> Extended search fixes and improvements

- jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/index/impl/ElasticsearchIndexManager.java
- jmix-search/search-opensearch/src/main/java/io/jmix/searchopensearch/index/impl/OpenSearchIndexManager.java
- jmix-search/search/src/main/java/io/jmix/search/index/impl/BaseIndexManager.java
- jmix-search/search/src/main/java/io/jmix/search/index/impl/ConfigurationComparingResult.java
- jmix-search/search/src/test/groovy/io/jmix/search/index/impl/BaseIndexManagerTest.groovy
> Incorrect behaviour of strategies: none, create-only #3789

- jmix-reports/reports/src/main/java/io/jmix/reports/libintegration/JmixHtmlFormatter.java
- jmix-reports/reports/src/main/java/io/jmix/reports/yarg/formatters/impl/AbstractFormatter.java
> HTML reports: apply format if exists only

- jmix-pivottable/pivottable-flowui/src/main/java/io/jmix/pivottableflowui/export/PivotTableExporterImpl.java
- jmix-pivottable/pivottable-flowui/src/main/java/io/jmix/pivottableflowui/view/PivotTableView.java
> Implement InitializingBean in PivotTableExporterImpl to initialize PivotTableExcelExporter 3820

- jmix-pivottable/pivottable-flowui-kit/src/main/java/io/jmix/pivottableflowui/kit/component/JmixPivotTable.java
> Better handling of PivotTable misconfiguration 3823

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/navigation/RouteSupport.java
> URL not updating after navigation jmix-framework/jmix#3654

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/impl/UrlQueryParametersFacetImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/DataGridFilterUrlQueryParametersBinder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/DataGridFilterUrlQueryParametersBinderProvider.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/GenericFilterUrlQueryParametersBinder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/GenericFilterUrlQueryParametersBinderProvider.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/HasInitialState.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/PaginationUrlQueryParametersBinder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/PaginationUrlQueryParametersBinderProvider.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/PropertyFilterUrlQueryParametersBinder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/urlqueryparameters/PropertyFilterUrlQueryParametersBinderProvider.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/View.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/ViewControllerUtils.java
Fixes:
- URL query parameters are applied multiple times jmix-framework/jmix#3345
- Unexpected behavior of the view with different URL query parameters jmix-framework/jmix#3661
> URL query parameters are applied multiple times

- jmix-core/core/src/main/java/io/jmix/core/event/AttributeChanges.java
Added `@Nullable` to the method `io.jmix.core.event.AttributeChanges.getOldCollection()` #3897
> fix bug #3897

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/UiProperties.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/filedownloader/JmixFileDownloader.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/download/DownloaderImpl.java
See: #3401
See also: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
> NPE on downloading PDF file in Chrome jmix-framework/jmix#3401

- jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/searching/strategy/impl/AllTermsAnyFieldElasticsearchSearchStrategy.java
- jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/searching/strategy/impl/AllTermsSingleFieldElasticsearchSearchStrategy.java
- jmix-search/search-elasticsearch/src/main/java/io/jmix/searchelasticsearch/searching/strategy/impl/PhraseElasticsearchSearchStrategy.java
- jmix-search/search-opensearch/src/main/java/io/jmix/searchopensearch/searching/strategy/impl/AllTermsAnyFieldOpenSearchSearchStrategy.java
- jmix-search/search-opensearch/src/main/java/io/jmix/searchopensearch/searching/strategy/impl/AllTermsSingleFieldOpenSearchSearchStrategy.java
- jmix-search/search-opensearch/src/main/java/io/jmix/searchopensearch/searching/strategy/impl/PhraseOpenSearchSearchStrategy.java
- jmix-search/search/src/main/java/io/jmix/search/searching/SearchUtils.java
> Fix search of FileRef fields within OOB search strategies. Misc fixes.

- jmix-search/search/src/main/java/io/jmix/search/index/mapping/fieldmapper/impl/EnumFieldMapper.java
> Extended search support for Enums

- jmix-search/search-flowui/src/main/java/io/jmix/searchflowui/component/SearchField.java
- jmix-search/search-flowui/src/main/java/io/jmix/searchflowui/view/result/SearchResultsView.java
> Repeated search within search result dialog window opens new dialog

- jmix-security/security-data/src/main/java/io/jmix/securitydata/impl/CurrentLocaleQueryParamValueProvider.java
- jmix-security/security-data/src/test/groovy/query_parameters/QueryParametersTest.groovy
Fixes: https://github.com/jmix-framework/jmix/issues/3958
> Added CurrentLocaleQueryParamValueProvider #3958

- jmix-templates/content/flowui/master-detail/controller.java
- jmix-templates/content/flowui/master-detail/controller.kt
… 'Remove' buttons enabled (3791)
> Opening item on master details view via double click keeps edit and remove buttons enabled (3791)

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/KeyCombination.java
- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/component/delegate/AbstractActionsHolderSupport.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/AbstractGridDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/impl/ViewActionsImpl.java
> Shortcut does not work when the focus is not in the input field jmix-framework/jmix#3730

- jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/entitycache/QueryKey.java
- jmix-data/eclipselink/src/test/groovy/cache/CachedQueryTest.groovy
- jmix-data/eclipselink/src/test/resources/test_support/test-app.properties
> NPE when executing cacheable query with null parameter

- jmix-bom/bom.gradle
Added SwaggerUI Addon to jmix-bom.
> [jmix-bom] ->Release 2.4 -> Swagger UI Add-on

- jmix-gradle-plugin/src/main/groovy/io/jmix/gradle/JmixPlugin.groovy
#3451
Added `cleanConf` gradle task to Jmix gradle plugin.
Task is automatically executed before `bootRun` task.
> Clean conf folder within Jmix plugin

- jmix-core/core/core.gradle
- jmix-core/core/src/main/java/io/jmix/core/CoreConfiguration.java
The initializer applies all defined org.springframework.boot.autoconfigure.ValidationConfigurationCustomizer beans to the configuration.
Fixes: #3662
> Set configuration initializer to JmixLocalValidatorFactoryBean

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/settings/component/binder/AbstractGridSettingsBinder.java
> Ignore only mismatched column keys in AbstractGridSettingsBinder jmix-framework/jmix#3746

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/impl/ActionsImpl.java
> Hot deploy of @ActionType annotated actions jmix-framework/jmix#4112

- jmix-translations/content/io/jmix/mapsflowui/messages.properties
- jmix-translations/content/io/jmix/mapsflowui/messages_ru.properties
See https://github.com/jmix-framework/jmix/issues/2832
> Ability to edit features on the map (2832)

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/impl/UrlQueryParametersFacetImpl.java
> Simultaneous use of UrlQueryParameters facets for filters breaks URL jmix-framework/jmix#4235

- jmix-authserver/authserver/src/main/java/io/jmix/authserver/AuthServerProperties.java
- jmix-authserver/authserver/src/main/java/io/jmix/authserver/request/AuthServerRequestCacheRequestMatcher.java
- jmix-authserver/authserver/src/main/java/io/jmix/authserver/request/package-info.java
- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/security/FlowuiVaadinWebSecurity.java
- jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/security/JmixViewPathRequestMatcher.java
- jmix-security/security/src/main/java/io/jmix/security/configurer/JmixRequestCacheRequestMatcher.java
See https://github.com/jmix-framework/jmix/issues/4259
> Authorization Code authentication flow is broken 4259

- jmix-rest/sample-rest/src/main/java/io/jmix/samples/rest/security/CarReadAllAttributesRole.java
- jmix-rest/sample-rest/src/test/java/entities/EntitiesControllerSecurityFT.java
- jmix-security/security/src/main/java/io/jmix/security/constraint/ExportImportEntityConstraint.java
Fixes https://github.com/jmix-framework/jmix/issues/4291
> Entity policy in export

- jmix-datatools/datatools/src/main/java/io/jmix/datatools/impl/EntityRestoreImpl.java
> Cannot restore entity via Entity Inspector (@MappedSuperclass -> @OnDeleteInverse) jmix-framework/jmix#4176

- jmix-security/security-oauth2-starter/security-oauth2-starter.gradle
- jmix-security/security-oauth2-starter/src/main/java/io/jmix/autoconfigure/securityoauth2/SecurityOAuth2AutoConfiguration.java
- jmix-security/security-oauth2/src/main/java/io/jmix/securityoauth2/token/store/JmixJdbcTokenStore.java
- jmix-security/security-oauth2/src/main/java/io/jmix/securityoauth2/token/store/cleanup/OAuth2ExpiredTokenCleaner.java
- jmix-security/security-oauth2/src/main/java/io/jmix/securityoauth2/token/store/cleanup/impl/InMemoryOAuth2ExpiredTokenCleaner.java
- jmix-security/security-oauth2/src/main/java/io/jmix/securityoauth2/token/store/cleanup/impl/JdbcOAuth2ExpiredTokenCleaner.java
- jmix-security/security-oauth2/src/main/java/io/jmix/securityoauth2/token/store/cleanup/impl/package-info.java
- jmix-security/security-oauth2/src/main/java/io/jmix/securityoauth2/token/store/cleanup/package-info.java
- jmix-security/security-oauth2/src/main/java/io/jmix/securityoauth2/token/store/package-info.java
- jmix-security/security-oauth2/src/main/resources/io/jmix/securityoauth2/liquibase/changelog/002-security-oauth2.xml
> Application generates oauth tokens without proper cleanup

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/Dialogs.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/impl/DialogsImpl.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/AbstractDialogWindow.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/DialogMode.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/AbstractWindowBuilder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/AbstractWindowBuilderProcessor.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/DetailWindowBuilder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/DetailWindowClassBuilder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/DialogWindowBuilder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/LookupWindowBuilder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/LookupWindowClassBuilder.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/builder/WindowBuilder.java
- jmix-tabbedmode/tabbedmode-flowui/src/main/java/io/jmix/tabbedmode/builder/dialog/TabbedModeDetailWindowBuilderProcessor.java
- jmix-tabbedmode/tabbedmode-flowui/src/main/java/io/jmix/tabbedmode/builder/dialog/TabbedModeLookupWindowBuilderProcessor.java
- jmix-tabbedmode/tabbedmode-flowui/src/main/java/io/jmix/tabbedmode/builder/dialog/TabbedModeWindowBuilderProcessor.java
> Support position API for Dialogs jmix-framework/jmix#4126

- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/delegate/AbstractGridDelegate.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/grid/DataGrid.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/grid/TreeDataGrid.java
> Aggregation value is not updated after item is changed using DataGrid's inline editor jmix-framework/jmix#4330

- jmix-audit/audit-flowui/src/main/java/io/jmix/auditflowui/view/entitylog/EntityLogView.java
- jmix-audit/audit-flowui/src/main/resources/META-INF/resources/styles/audit-styles.css
- jmix-audit/audit-flowui/src/main/resources/io/jmix/auditflowui/module.properties
- jmix-audit/audit-flowui/src/main/resources/io/jmix/auditflowui/view/entitylog/entity-log-view.xml
- jmix-audit/audit-flowui/src/main/resources/io/jmix/auditflowui/view/sessions/user-sessions-view.xml
> Entity log view improvements jmix-framework/jmix#3502

- jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/element/StudioElements.java
- jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/container/HorizontalLayoutLoader.java
- jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/layout.xsd
- jmix-flowui/flowui/src/test/groovy/component_xml_load/ContainerXmlLoadTest.groovy
- jmix-flowui/flowui/src/test/java/component_xml_load/screen/ContainerView.java
- jmix-flowui/flowui/src/test/resources/component_xml_load/screen/container-view.xml
> Provide the ability to place components in slots for HorizontalLayout in XML jmix-framework/jmix#4403

- jmix-rest/rest/src/main/java/io/jmix/rest/impl/service/filter/RestFilterParser.java
> REST filter passing via GET returns Bad Request  #3829

- jmix-core/core/src/main/java/io/jmix/core/FileRef.java
> Inconsistent handling of file extensions in FileStorage implementations #4475

- jmix-reports/reports-flowui/src/main/resources/io/jmix/reportsflowui/view/history/report-execution-dialog-view.xml
> The history of report execution using an action in ListViews does not load data immediately #4748
