jmix-framework/jmix

jmix-translations/content/io/jmix/businesscalendar/messages_de.properties, jmix-translations/content/io/jmix/businesscalendarui/messages_de.properties, jmix-translations/content/io/jmix/graphql/messages_de.properties, jmix-translations/content/io/jmix/notifications/messages_de.properties, jmix-translations/content/io/jmix/notificationsui/messages_de.properties
* german translations for `graphql`, `notifications` and `business-calendar`
=> add german translations for notifications, graphql and business-calendar

jmix-ui/ui/src/main/java/io/jmix/ui/sys/ControllerUtils.java, jmix-ui/ui/src/test/groovy/util/ControllerUtilsTest.groovy
Fixes issue:
https://github.com/jmix-framework/jmix/issues/1018
ControllerUtils - getLocationWithoutParams from encoded url was failing:
when:
URI encodedUrl = new URI("http://localhost:8080/#login?redirectTo=employees%2Fview")
then:
ControllerUtils.getLocationWithoutParams(encodedUrl) == "http://localhost:8080/"
Now all tests pass successfully...
=> ControllerUtils - getLocationWithoutParams from encoded url fix... #1018

jmix-ui/ui/src/main/java/io/jmix/ui/sys/ControllerUtils.java, jmix-ui/ui/src/test/groovy/util/ControllerUtilsTest.groovy
This PR fixes #1422.
* `ControllerUtils::getLocationWithoutParams` now tries to remove the raw query string from the string instead of the URL decoded variant from `java.net.URI` (logic is now similar as for the fragment part removal)
=> fix #1422 - correct handling of URL encoded query parameters

jmix-translations/content/io/jmix/uiexport/messages.properties, jmix-translations/content/io/jmix/uiexport/messages_ru.properties, jmix-ui/ui-export/src/main/java/io/jmix/uiexport/ExportActionProperties.java, jmix-ui/ui-export/src/main/java/io/jmix/uiexport/UiExportConfiguration.java, jmix-ui/ui-export/src/main/java/io/jmix/uiexport/action/ExcelExportAction.java, jmix-ui/ui-export/src/main/java/io/jmix/uiexport/action/ExportAction.java, jmix-ui/ui-export/src/main/java/io/jmix/uiexport/exporter/ExportMode.java, jmix-ui/ui-export/src/main/java/io/jmix/uiexport/exporter/excel/AllRecordsExporter.java, jmix-ui/ui-export/src/main/java/io/jmix/uiexport/exporter/excel/ExcelExporter.java, jmix-ui/ui-export/src/main/java/io/jmix/uiexport/exporter/json/JsonExporter.java, jmix-ui/ui-export/src/main/resources/io/jmix/uiexport/messages.properties
A new exporting option has been added to the Excel Export action: "All rows". It exports all records from the database taking into account applied filter and initial data loader query from the screen.
Loading is performed using batches. The batch size may be configured using the following application property:
```
jmix.ui.exportaction.export-all-batch-size=2000
```
The default batch size is 1000.
Excel file now can be constructed using streaming POI API (SXSSF). It is turned on by default. To turn it off use the property:
```
jmix.ui.exportaction.excel.use-sxssf=false
```
Limitations:
* When a TreeTable or TreeDataGrid is exported no padding will be added to the column with hierarchy property.
* When a group table is exported, no grouping will be added to the excel file.
* Exporting of …
=> Export All functionality in the Excel export action

jmix-templates/content/project/addon-kotlin/${module_name}/src/test/kotlin/${project_rootPath}/${project_id.capitalize()}TestConfiguration.kt, jmix-templates/content/project/addon-kotlin/${module_name}/src/test/resources/${project_rootPath}/test-app.properties, jmix-templates/content/project/addon/${module_name}/src/test/java/${project_rootPath}/${project_id.capitalize()}TestConfiguration.java, jmix-templates/content/project/addon/${module_name}/src/test/resources/${project_rootPath}/test-app.properties
The `test-app.properties` file with Liquibase config has been added to add-on templates for Java and Kotlin.
=> Default test in add-on fails because of invalid Liquibase configuration 1533

jmix-core/core/src/main/java/io/jmix/core/Metadata.java, jmix-core/core/src/main/java/io/jmix/core/impl/EmbeddedIdEntityInitializer.java, jmix-core/core/src/main/java/io/jmix/core/impl/MetadataImpl.java, jmix-core/core/src/main/java/io/jmix/core/impl/UnconstrainedDataManagerImpl.java
https://github.com/jmix-framework/jmix/issues/1451
- Override 'create' methods with externally provided entity id.
- Set provided id before apply entity initializers.
- Update `EmbeddedIdEntityInitializer`: create new embedded id instance only if id is not set.
=> DataManager.getReference() increments underlying sequence #1451

jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/support/JmixEclipseLinkJpaVendorAdapter.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/exception/ConstraintViolationExceptionHandler.java
- Automatical bean validation on persistence layer is enabled
- Can be disabled by setting `javax.persistence.validation.mode` app property to `NONE`
- Validator groups can be configured by the following application properties (full class name required as value): `jakarta.persistence.validation.group.pre-persist`, `jakarta.persistence.validation.group.pre-update`, `jakarta.persistence.validation.group.pre-remove`. `Default` group by default.
- JmixLocalValidatorFactoryBean with Jmix-specific message interpolator is used as validation factory for auto validation (the same as for the manual validation on UI\REST side)
=> [PR] Bean validation on persistence layer #1368

jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/JmixServiceInitListener.java
Fix for https://github.com/jmix-framework/jmix/issues/1851
**Solution**
An Add-on may contain a file with custom styles under `META-INF/resources/` directory. In order to add these styles to the resulting app the `jmix.ui.import-styles` property must be added to the `module.properties` file. The value of the property is a relative path from `META-INF/resources/`, e.g. `jmix.ui.import-styles = addon-styles/test.css`
Custom styles are added as `<style type="text/css">` to the `head` element, e.g.:
```
<style type="text/css">
.test {
color: red;
}
.test-2 {
color: green;
}
.test-3 {
color: blue;
}
</style>
```
=> Pluggable styles from addons

jmix-core/core/src/main/java/io/jmix/core/InstanceNameProvider.java, jmix-core/core/src/main/java/io/jmix/core/impl/InstanceNameProviderImpl.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/StandardDetailView.java, jmix-flowui/flowui/src/main/resources/io/jmix/flowui/messages.properties, jmix-translations/content/io/jmix/flowui/messages.properties, jmix-translations/content/io/jmix/flowui/messages_ckb.properties, jmix-translations/content/io/jmix/flowui/messages_fr.properties, jmix-translations/content/io/jmix/flowui/messages_it.properties, jmix-translations/content/io/jmix/flowui/messages_nl.properties, jmix-translations/content/io/jmix/flowui/messages_ru.properties
Fixes: https://github.com/jmix-framework/jmix/issues/1886
* `InstanceNameProvider` now contains a method to check if an entity class has `@IntanceName`. 
* Added a new message key: `info.EntitySaved.short`
=> Improve display of object save message (1886)

jmix-authserver/authserver-starter/src/main/java/io/jmix/autoconfigure/authserver/AuthServerAutoConfiguration.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/AuthServerProperties.java
Application properties for specifying the login form view name and login form URL have been introduced:
```
jmix.authserver.login-page-view-name=as-login.html
jmix.authserver.login-page-url=/as-login
```
In a application users may create a custom login page, e.g. `src/main/resources/templates/my-as-login.html` and define a property:
```
jmix.authserver.login-page-view-name=my-as-login.html
```
=> Custom login form for authorization server 1098

jmix-core/core/src/main/java/io/jmix/core/impl/importexport/EntityImportExportImpl.java
Fixes json export for removed entities that have 'Soft Delete' trait. See https://github.com/jmix-framework/jmix/issues/1682
=> Soft-deleted records are not available in Entity Inspector #1682

jmix-rest/rest/src/main/java/io/jmix/rest/security/impl/RestAuthorizedUrlsProvider.java
See https://github.com/jmix-framework/jmix/issues/1626
=> jmix.rest.anonymous-url-patterns doesn't work if multiple URLs separated by a comma with a space #1626

jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/component/StudioLayouts.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/loader/container/AbstractLayoutLoader.java, jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/layout.xsd, jmix-flowui/flowui/src/test/groovy/component_xml_load/ContainerXmlLoadTest.groovy, jmix-flowui/flowui/src/test/resources/component_xml_load/screen/container-view.xml
See: #2293
The `loadThemeNames(ThemableLayout, Element)` method will be moved to the `AbstractComponentLoader` class if it is needed in other places besides `AbstractLayoutLoader`.
=> Ability to define theme names for layouts jmix-framework/jmix#2293

jmix-core/core/src/main/java/io/jmix/core/QueryParamValueProvider.java, jmix-core/core/src/main/java/io/jmix/core/impl/QueryParamValuesManager.java, jmix-data/data/src/main/java/io/jmix/data/impl/JpqlQueryBuilder.java, jmix-data/data/src/main/java/io/jmix/data/impl/SessionQueryParamValueProvider.java, jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/JmixEclipseLinkQuery.java, jmix-data/eclipselink/src/test/java/test_support/TestQueryParamValueProvider.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/facet/impl/DataLoadCoordinatorImpl.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/facet/DataLoadCoordinatorFacetProvider.java, jmix-flowui/flowui/src/test/groovy/facet/data_load_coordinator/DataLoadCoordinatorFacetTest.groovy, jmix-flowui/flowui/src/test/java/facet/data_load_coordinator/screen/DlcAutoProvidedParamTestScreen.java, jmix-flowui/flowui/src/test/resources/facet/data_load_coordinator/screen/dlc-auto-provided-param-screen.xml, jmix-security/security-data/src/main/java/io/jmix/securitydata/impl/CurrentUserQueryParamValueProvider.java
Moved `QueryParamValueProvider` and `QueryParamValuesManager` to core. 
Now `QueryParamValuesManager` is used in `DataLoadCoordinatorImpl#configureAutomatically()` to filter out parameters that are provided by a `QueryParamValueProvider` .
=> DataLoadCoordinator and session attribute parameters (2nd attempt)

jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/element/StudioElements.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/xml/layout/support/DataLoaderSupport.java, jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/layout.xsd
Improvements for https://github.com/jmix-framework/jmix/issues/1923
Changed:
* `searchStringFormat` attribute assumes `inputString` as a value placeholder instead of `searchString`
Added: 
* Nested `query` element, similar to data loaders
* Nested `fetchPlan` element that defines inline fetch plan, similar to data containers
Note: the `fetchPlan` attribute is still present and defines named fetch plan, same as for data containers
=> Support Items fetch callback (improvements)

jmix-data/data/src/main/java/io/jmix/data/Sequence.java
Added a way (equals and hashcode) to compare two objects of Sequence type
Issue - [1497](https://github.com/jmix-framework/jmix/issues/1497)
=>  Equals and hashcode aren't defined in io.jmix.data.Sequence

jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/view/categoryattr/CategoryAttributesDetailView.java
I choose to concate category name and attribute name by **_** instead of trying to predict which case user chose for name:
samples:
1. How to concate when category name is FULLUPPERCASE or fULLCASEWITHUNDERCUT
2. Same as first but for attribute name
Besides, we can do not change names and just concate both with "_" and we will prevent any misunderstood cases
Advantages:
1. We will not take any responsibility of name changing
2. More understandable name-code (if names contains more then one word / contains same words => mass of camelcase)
3. Real word split and user always sees what category he uses (+SomeCategory_SomeName)
=> Fix that the name in the generated Code field does not start with a capital letter

jmix-gradle-plugin/src/main/groovy/io/jmix/gradle/EnhancingAction.groovy, jmix-gradle-plugin/src/main/groovy/io/jmix/gradle/JmixExtension.groovy
During entities enhancement, the Jmix Gradle plugin evaluates the checksum of enhanced entities classes and saves it to a file in the temporary directory. When next compilation is executed, the plugin checks that entity classes inside the project build directory are the same as the saved ones (have the same checksum). There will be difference if any entity class is changed or a new entity is created. In this case the build directory will contain a modified (non-enhanced) entity class. If such differences are found then entity enhancing step will be run.
To disable this behavior and always enhance all entities on each compilation the following config should be added to the build.gradle:
```
jmix {
entitiesEnhancing {
skipUnmodifiedEntitiesEnhancing = false
}
}
```
By default, the entities …
=> Skip enhancing of entities if entities weren't changed

jmix-flowui/flowui-themes/src/main/resources/META-INF/resources/themes/jmix-lumo/component/vaadin-form-layout.css, jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/filter/SingleFilterComponentBase.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/logicalfilter/GroupFilter.java
See: #2745
New approach is implemented: now, overflowing text will be hidden.
A title for the label component is also added.
=> Fields in genericFilter are not aligned if one label is longer jmix-framework/jmix#2745

jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/impl/DynAttrFacetInfo.java, jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/impl/FormEmbeddingStrategy.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/formlayout/JmixFormLayout.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/grid/DataGrid.java
Duplicated from issue comment(i created an issues):
There is not errors for master detail screen.
Bug was produced by service that finds elements with "null" id. 
So, we need to fix that method, ignore searching elements without IDs(formLayout and dataGrid).
Issue causes following issues:
* No root form layout id inside root form: https://github.com/jmix-framework/jmix/issues/2958
* No validation inside MasterDetailsView's form layout https://github.com/jmix-framework/jmix/issues/2959
We would not support detail's view behaviour for form inside it, but we can fix it for scaffolded views
=> fix NullPointerException: Master-detail view + DynamicAttribute

jmix-flowui/flowui-starter/src/main/java/io/jmix/autoconfigure/flowui/FlowuiAutoConfiguration.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/UiProperties.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/LogoutSupport.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/UiAccessChecker.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/sys/vaadin/SecurityContextHolderAtmosphereInterceptor.java, jmix-oidc/oidc-starter/src/main/java/io/jmix/autoconfigure/oidc/OidcAutoConfiguration.java, jmix-oidc/oidc/oidc.gradle, jmix-oidc/oidc/src/main/java/io/jmix/oidc/OidcVaadinWebSecurity.java, jmix-oidc/oidc/src/test/java/io/jmix/oidc/OidcTest.java, jmix-security/security-flowui-starter/src/main/java/io/jmix/autoconfigure/securityflowui/NavigationAccessControlAutoConfiguration.java, jmix-security/security-flowui-starter/src/main/java/io/jmix/autoconfigure/securityflowui/SecurityFlowuiAutoConfiguration.java, jmix-security/security-flowui-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/FlowuiSecurityConfiguration.java, jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/access/JmixNavigationAccessChecker.java, jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/access/UiViewAccessChecker.java, jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/access/UiViewAccessCheckerInitializer.java, jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/authentication/LoginViewSupport.java, jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/security/FlowuiVaadinWebSecurity.java
Previously `FlowuiSecurityConfiguration` contained the code copied from `VaadinWebSecurity` class with some minor modifications. Starting with Jmix 2.3, the FlowUI security configuration **extends** VaadinWebSecurity. New `FlowuiVaadinWebSecurity` class was introduced. 
If users need to disable standard FlowUI security configuration they should use the following application property for that:
```
jmix.flowui.use-default-security-configuration=false
```
A new class `JmixNavigationAccessChecker` was introduced. It implements the Vaadin `NavigationAccessChecker` introduced in Vaadin 24.3 (see [docs](https://vaadin.com/docs/latest/security/advanced-topics/navigation-access-control)). This mechanism replaces the `ViewAccessChecker` used previously.
Since Spring Security 6 the SecurityContext …
=> Rework FlowUI security configuration

jmix-core/core/src/main/java/io/jmix/core/BeanExclusionProcessor.java, jmix-core/core/src/main/java/io/jmix/core/CoreConfiguration.java
=> jmix.core.exclude-beans defined in project overrides values from Jmix modules (3129)

jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/StandardDetailView.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/View.java
* Fix for https://github.com/jmix-framework/jmix/issues/2992 is suitable for a detail view only as it's the main consumer of view attributes and backward navigation.
* Now, `View` has more generic solution, suitable in most cases for all views. `StandardDetailView` implements its own logic.
* Corresponding methods became `protected`, so it's possible to override them.
=> ApplicationListener defined in main view doesn't work after navigating to another view (3222)

jmix-data/data/src/main/java/io/jmix/data/impl/JpqlQueryBuilder.java, jmix-data/eclipselink/src/test/groovy/not_only_jpa/JpqlBuilderWithNonJpaPropertiesTest.groovy, jmix-flowui/flowui/src/main/java/io/jmix/flowui/UiComponentProperties.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/app/filter/condition/AddConditionView.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/component/genericfilter/FilterMetadataTools.java
This implementation removes the restriction on JPA properties for the filter. Thus, entities and non-persistent properties are added to a set of meta property paths available for filtering.
E.g.: DTO Entity:
```java
@JmixEntity
public class TestEntity {
@JmixGeneratedValue
@JmixId
private UUID id;
@InstanceName
private String name;
public String getName() {
return name;
}
public void setName(String name) {
this.name = name;
}
public UUID getId() {
return id;
}
public void setId(UUID id) {
this.id = id;
}
}
````
The properties become available in the `Add Condition` dialog:
When you select any property, the **query** is modified in the data loader. This information is passed to the `LoadContext`, which can be processed in the `LoadDelegate`:
The you can use this information to process a …
=> Using DTO entities and non-persistent attributes in filter components

jmix-reports/reports-flowui/src/main/java/io/jmix/reportsflowui/view/reportwizard/template/generators/XlsxGenerator.java, jmix-reports/reports/src/main/java/io/jmix/reports/yarg/formatters/impl/xlsx/Document.java, jmix-reports/reports/src/main/java/io/jmix/reports/yarg/formatters/impl/xlsx/Range.java, jmix-reports/reports/src/main/java/io/jmix/reports/yarg/formatters/impl/xlsx/StyleSheet.java, jmix-reports/reports/src/main/java/io/jmix/reports/yarg/formatters/impl/xlsx/hints/RowAutoHeightXlsxHint.java, jmix-reports/reports/src/main/java/io/jmix/reports/yarg/formatters/impl/xlsx/hints/XslxHintProcessor.java
1. Add `RowAutoHeightXlsxHint` class that recalculates a row height in the following way: 
- For each cell: calculate a required height as sum of heights of each line of the cell value. 
- Find max height from the calculated cell heights and provided row height 
- Set found max value as row height This logic works if there is a defined name starting with "hint_rowAutoHeight" in the XLSX report template.
5. Report Wizard: enable row height calculation using RowAutoHeightXlsxHint for XLSX reports created from wizard.
=> 1269: When forming a long row, the height of the cell is not recalculated 

jmix-authserver/authserver-starter/src/main/java/io/jmix/autoconfigure/authserver/AuthServerAutoConfiguration.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/principal/AuthServerAuthenticationPrincipalResolver.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/principal/package-info.java, jmix-core/core/src/main/java/io/jmix/core/security/AuthenticationPrincipalResolver.java, jmix-core/core/src/main/java/io/jmix/core/security/impl/CurrentAuthenticationImpl.java
The issue: #2051 
`AuthenticationPrincipalResolver` mechanism has been introduced.
This is required to make the `CurrentAuthentication.getUser()` return an instance of actual user class when authenticating using the access token obtained with Authorization Server add-on.
=> AuthenticationPrincipalResolver mechanism introduced

jmix-awsfs/awsfs/src/main/java/io/jmix/awsfs/AwsFileStorage.java
- Reduce the number of requests to upload small files
- Replace BufferedInputStream.available() (#327)
- Reduce memory allocation for multipart upload
- Make upload bucket name thread safe when refresh s3 client
=> Improvment awsfs save stream

jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/AdaptiveNumberDatatype.java, jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/BooleanDatatype.java, jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/CharacterDatatype.java, jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/DoubleDatatype.java, jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/FloatDatatype.java, jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/IntegerDatatype.java, jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/LongDatatype.java, jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/NumberDatatype.java, jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/ShortDatatype.java, jmix-core/core/src/main/java/io/jmix/core/metamodel/datatype/impl/UuidDatatype.java, jmix-core/core/src/main/resources/io/jmix/core/messages.properties, jmix-translations/content/io/jmix/core/messages.properties, jmix-translations/content/io/jmix/core/messages_ru.properties
#3284
In the issue the app execution does not get into the validator. Parse exception for jmix datatypes rises before. So localised messages were added to the ParseException constructor.
=> The message about the wrong data type cannot be localised 3284

jmix-core/core/src/main/java/io/jmix/core/impl/session/ThreadLocalSessionData.java, jmix-data/data/src/main/java/io/jmix/data/impl/SessionQueryParamValueProvider.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/backgroundtask/impl/BackgroundWorkerImpl.java
Proposed changes allow to use JPQL row-level policies that use session attributes in queries run from background tasks.
Sample project: [session-attrs-bg-sample.zip](https://github.com/user-attachments/files/15926812/session-attrs-bg-sample.zip)
=> Thread local session attributes in background tasks

jmix-flowui/flowui/src/main/java/io/jmix/flowui/asynctask/DelegatingSecurityRunnable.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/asynctask/DelegatingSecuritySupplier.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/asynctask/UiAsyncTaskProperties.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/asynctask/UiAsyncTasks.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/asynctask/package-info.java
The new API is intended to be used instead of [Background Task](https://docs.jmix.io/jmix/flow-ui/background-tasks.html) in simple cases. Background tasks are powerful, but sometimes users don't need all their featues like showing a modal dialog or handling the task execution progress.
For a problem that sounds like "load some data in the background and after the data is loaded update some UI component" the new `UiAsyncTasks` service may be used.
Usage examples:
```java
uiAsyncTasks.supplierConfigurer(() -> {
return customerService.loadAllCustomersForCurrentUser();
})
.withResultHandler(customers -> {
customersDc.getMutableItems().addAll(customers);
notifications.create("Customers loaded: " + customers.size())
.show();
})
.supplyAsync();
```
When the asynchronous task returns no result, …
=> Simplified API for UI asynchronous tasks

jmix-flowui/flowui-kit/src/main/java/io/jmix/flowui/kit/meta/action/StudioGridExportActions.java, jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/GridExportProperties.java, jmix-gridexport/gridexport-flowui/src/main/java/io/jmix/gridexportflowui/action/ExportAction.java
See: #3497
All options are visible if it possible:
A new application property has been created: `jmix.gridexport.default-export-modes`.
The property defined a default set of options for export modes for `ExportAction`.
The order of the options in the application property is taken into account. Options will be added in the order they are added using property:
The default value of the property remains the same as in the previous implementation: `ALL_ROWS, CURRENT_PAGE, SELECTED_ROWS`
* `io.jmix.gridexportflowui.action.ExportAction#setAvailableExportModes`
* `io.jmix.gridexportflowui.action.ExportAction#withAvailableExportModes`
Provides the ability to set available export modes for each `exportAction` separately.
Modes set via API have priority over modes set by default using …
=> Configure export options for the Grid export action jmix-framework/jmix#3497

jmix-flowui/flowui/src/main/java/io/jmix/flowui/Dialogs.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/impl/DialogsImpl.java
See: #3343 
`build()` and `open()` methods have been added to all dialog builders.
Why do you need a build method?
After the `build()` method, you can customize the `dialog`: add listeners for closing/opening. And then manually open the `dialog` using the `Dialog#open()` method. If we'll provide only the `Builder#open()` method, it will be impossible to add a listener for opening.
----
Features of the implementation of the `BackgroundTaskDialogBuilder#build` method.
Here is the old implementation of the `BackgroundTaskDialogBuilder#open` method:
```java
@Override
public void open() {
if (isIndeterminateMode()) {
progressTextSpan.setVisible(false);
progressBar.setIndeterminate(true);
} else {
progressTextSpan.setVisible(true);
}
updateProgress(0);
dialog.open();
startExecution();
}
```
As …
=> Builders in Dialogs bean should return Dialog instance when it is opened jmix-framework/jmix#3343

jmix-dynattr/dynattr-flowui/src/main/java/io/jmix/dynattrflowui/view/categoryattr/CategoryAttributesDetailView.java
See issue #3638
**Problem:** In the `refreshAttributesUI()` method, both `defaultStringField` and `defaultEnumField` are cleared due to the following code:
```java
if (!visible && component instanceof HasValue) {
((HasValue<?, ?>) component).clear();
}
```
When the `defaultEnumField` component is processed, it gets cleared, which triggers a listener attached to it. This listener also clears the `defaultStringField`.
The listener is added in the `initDefaultEnumField()` method, which is called during every initialization:
```java
private void initDefaultEnumField() {
//...
defaultEnumField.addValueChangeListener(e -> getEditedEntity().setDefaultString(e.getValue()));
if (StringUtils.isNotBlank(getEditedEntity().getDefaultString())) { …
```
=> fix default value of dynamic attribute #3638

jmix-security/security-flowui/src/main/java/io/jmix/securityflowui/role/UiMinimalPolicies.java, jmix-templates/content/project/application-kotlin/src/main/kotlin/${project_rootPath}/security/UiMinimalRole.kt, jmix-templates/content/project/application/src/main/java/${project_rootPath}/security/UiMinimalRole.java
This fixes #3580 for new projects.
The idea is to create a base interface for `UiMinimalRole` in the framework and put all system policies there. Then we'll be able to add new minimal system policies and propagate them to app projects without any migrations.
=> Amend UI minimal policies (3580)

jmix-core/core/src/main/java/io/jmix/core/EntityEntry.java, jmix-core/core/src/main/java/io/jmix/core/EntityStates.java, jmix-core/core/src/main/java/io/jmix/core/entity/BaseEntityEntry.java, jmix-core/core/src/main/java/io/jmix/core/entity/LoadedPropertiesInfo.java, jmix-core/core/src/main/java/io/jmix/core/impl/CachingLoadedPropertiesInfo.java, jmix-core/core/src/main/java/io/jmix/core/impl/CorePersistentAttributesLoadChecker.java, jmix-core/core/src/main/java/io/jmix/core/impl/LoadedPropertiesInfoFactory.java, jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/EclipselinkPersistenceSupport.java, jmix-data/eclipselink/src/main/java/io/jmix/eclipselink/impl/lazyloading/AbstractValueHolder.java, jmix-data/eclipselink/src/test/groovy/entity_states/EntityStatesIsLoadedTest.groovy, jmix-data/eclipselink/src/test/groovy/lazy_loading/EmbeddedIdReferenceTest.groovy, jmix-data/eclipselink/src/test/java/test_support/entity/sales/OrderLine.java, jmix-data/eclipselink/src/test/resources/logback-test.xml, jmix-flowui/flowui/src/test/resources/logback-test.xml, jmix-restds/restds/src/main/java/io/jmix/restds/impl/RestDataStore.java, jmix-restds/restds/src/main/java/io/jmix/restds/impl/RestDsLoadedPropertiesInfoFactory.java, jmix-restds/restds/src/main/java/io/jmix/restds/impl/StaticLoadedPropertiesInfo.java
Introduced `LoadedPropertiesInfo` interface that can be set for any entity instance in its `EntityEntry`. Different types of entities can have different implementations of this interface.
The `LoadedPropertiesInfo` of an entity instance, if its is set, is used by `EntityStates.isLoaded()` instead of direct call to `PersistentAttributesLoadChecker`.
For JPA entities, `CachingLoadedPropertiesInfo` is used by default. If the `jmix.core.disable-caching-loaded-properties` property is true in the project, the `CachingLoadedPropertiesInfo` is not created and behavior is identical to the previous.
JPA entities in managed state do not have `CachingLoadedPropertiesInfo`, because automatic loading of attributes is uncontrollable and cache invalidation is impossible. So the isLoaded check goes …
=> Improve performance of EntityStates.isLoaded operation

jmix-core/core/src/main/java/io/jmix/core/FileStorageLocator.java, jmix-core/core/src/main/java/io/jmix/core/impl/FileStorageLocatorImpl.java, jmix-restds/restds/src/main/java/io/jmix/restds/filestorage/RestFileStorage.java, jmix-restds/restds/src/main/java/io/jmix/restds/filestorage/package-info.java, jmix-restds/restds/src/main/java/io/jmix/restds/impl/RestDataStore.java, jmix-restds/restds/src/main/java/io/jmix/restds/impl/RestSaveContextProcessor.java, jmix-restds/restds/src/test/java/filestorage/FileStorageTest.java, jmix-restds/restds/src/test/java/rest_ds/RestSaveContextProcessorTest.java, jmix-restds/restds/src/test/java/test_support/TestRestDsConfiguration.java, jmix-restds/restds/src/test/java/test_support/entity/Customer.java, jmix-restds/sample-rest-service/sample-rest-service.gradle, jmix-restds/sample-rest-service/src/main/java/io/jmix/samples/restservice/app/SampleDataInitializer.java, jmix-restds/sample-rest-service/src/main/java/io/jmix/samples/restservice/entity/Customer.java, jmix-restds/sample-rest-service/src/main/resources/io/jmix/samples/restservice/liquibase/changelog/020-init-customer.xml
Created `RestFileStorage` implementation of `FileStorage` interface that loads and saves files using the `/files` endpoints of the generic REST. 
`RestFileStorage` is intended to be used together with the REST DataStore.
To register a `RestFileStorage` in the application, define a bean:
```
@Bean
FileStorage backendFileStorage() {
return new RestFileStorage("backend", "fs");
}
```
Here 'backend' is the name of REST DataStore representing the remote application and 'fs' is the name of the corresponding file storage in the remote application.
=> Simplify access to FileStorage through generic REST

jmix-bom/bom.gradle, jmix-core/core/core.gradle, jmix-core/core/src/main/java/io/jmix/core/EntityUuidGenerator.java, jmix-core/core/src/main/java/io/jmix/core/UuidProvider.java, jmix-core/core/src/main/java/io/jmix/core/entity/KeyValueEntity.java, jmix-core/core/src/main/java/io/jmix/core/impl/GeneratedIdEntityInitializer.java, jmix-core/core/src/test/groovy/entity_uuid/EntityUuidGeneratorTest.groovy, jmix-reports/reports-flowui/src/main/java/io/jmix/reportsflowui/view/report/ReportDetailView.java, jmix-reports/reports-flowui/src/main/java/io/jmix/reportsflowui/view/report/ReportListView.java
I have chosen https://github.com/f4b6a3/uuid-creator library because it can generate increasing UUIDs within a millisecond (see [wiki](https://github.com/f4b6a3/uuid-creator/wiki/1.7.-UUIDv7)). I couldn't do the same with the alternative https://github.com/cowtowncoder/java-uuid-generator.
=> Use UUIDv7 for entity identifiers

jmix-flowui/flowui/src/main/java/io/jmix/flowui/model/DataContext.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/model/impl/DataContextImpl.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/model/impl/NoopDataContext.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/ChangeTracker.java, jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/StandardDetailView.java, jmix-flowui/flowui/src/test/groovy/data_components/DataContextTest.groovy
Introduced `io.jmix.flowui.model.DataContext#clearChanges` and  `io.jmix.flowui.view.ChangeTracker#clearChanges` methods.
=> Ability to clear "modified" state of a detail view

jmix-templates/content/flowui/bpm-advanced-task-list/controller.java, jmix-templates/content/flowui/bpm-advanced-task-list/controller.kt, jmix-templates/content/flowui/bpm-advanced-task-list/descriptor.xml, jmix-templates/content/flowui/bpm-advanced-task-list/settings.xml, jmix-templates/content/flowui/bpm-process-form/settings.xml
1. Add a new template for advanced implementation of My tasks list view
2. Template is available if the BPM add-on is used in the project (mapped by tag in settings.xml)
3. Advanced implementation suggests out-of-box:
- User tasks that current user can perform or claim are shown in the DataGrid. Shown columns: task name, process definition name, creation date and due date.
- A panel with custom filters for task name, process definition name, type of assignment (all tasks available for the current user, assigned and group tasks). Filter panel can be shown/hidden by clicking the button. A count of the applied filters are shown on the button.
- Sort tasks by name/due date/creation date
- Opening a task form for the selected task
4. User tasks are loaded using Flowable Java API
5. Update …
=> Re-design the My tasks list view #3752

jmix-authserver/authserver-starter/authserver-starter.gradle, jmix-authserver/authserver-starter/src/main/java/io/jmix/autoconfigure/authserver/AuthServerAutoConfiguration.java, jmix-authserver/authserver/authserver.gradle, jmix-authserver/authserver/src/main/java/io/jmix/authserver/AuthServerProperties.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/service/OracleJdbcOAuth2AuthorizationService.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/service/cleanup/OAuth2ExpiredTokenCleaner.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/service/cleanup/impl/InMemoryOAuth2ExpiredTokenCleaner.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/service/cleanup/impl/JdbcOAuth2ExpiredTokenCleaner.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/service/cleanup/impl/package-info.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/service/cleanup/package-info.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/service/mapper/DefaultOAuth2TokenUserMixin.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/service/mapper/JdbcOAuth2AuthorizationServiceObjectMapperCustomizer.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/service/mapper/package-info.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/service/package-info.java, jmix-authserver/authserver/src/main/resources/io/jmix/authserver/liquibase/changelog.xml, jmix-authserver/authserver/src/main/resources/io/jmix/authserver/liquibase/changelog/001-authserver.xml, jmix-authserver/authserver/src/main/resources/io/jmix/authserver/module.properties
See #1872
`jmix.authserver.use-in-memory-authorization-service` application property. False by default.
Table `oauth2_authorization` was added.
- `JdbcOAuth2AuthorizationService` is used for all databases except Oracle.
- `OracleJdbcOAuth2AuthorizationService` is used for Oracle database (Oracle-specific work with LOB data). 
- `InMemoryOAuth2ExpiredTokenCleaner` is used if feature is disabled.
Tokens with project `User` entity as principal (e.g. 'password' grant type) requires a mixin to perform deserialization.
Default mixin `DefaultOAuth2TokenUserMixin` is provided by addon. It also excludes `password` field from being serialized to token metadata.
`JdbcOAuth2AuthorizationServiceObjectMapperCustomizer` interface was introduced to be implemented as a bean on the project side. It allows …
=> 1872 authorization server must use jdbcoauth2authorizationservice

jmix-rest/rest/src/main/java/io/jmix/rest/impl/openapi/OpenAPIGeneratorImpl.java
Fixes #4264
Examples:
```java
@RestService("petclinic_OwnerRegistrationService")
public class OwnerRegistrationService {
@Autowired
protected DataManager dataManager;
@RestMethod(value = "registerOwner", httpMethods = RestHttpMethod.POST)
public Owner registerOwner(String firstName, String lastName) {
return dataManager.create(Owner.class);
};
}
```
leads to the following OpenAPI spec:
```java
@RestService("petclinic_OwnerRegistrationService")
public class OwnerRegistrationService {
@Autowired
protected DataManager dataManager;
@RestMethod(value = "registerOwner", httpMethods = RestHttpMethod.GET)
public Owner registerOwner(String firstName, String lastName) {
return dataManager.create(Owner.class);
};
}
```
leads to the following OpenAPI spec:
```java …
```
=> #4264 - fix wrong openapi spec generation for service method http methods

jmix-data/data/src/main/java/io/jmix/data/impl/jpql/generator/ConditionJpqlGenerator.java
Fixes #3980 
The [KeyValuePropertyConditionGenerator#L43](https://github.com/jmix-framework/jmix/blob/e2b937f0644ad0e4782741596426ccf7ad26d640/jmix-data/data/src/main/java/io/jmix/data/impl/jpql/generator/KeyValuePropertyConditionGenerator.java#L43) (required for filtering KeyValueCollections) checks that the context has getSelectedExpressions() != null, however, in [ConditionJpqlGenerator#L74](https://github.com/jmix-framework/jmix/blob/e2b937f0644ad0e4782741596426ccf7ad26d640/jmix-data/data/src/main/java/io/jmix/data/impl/jpql/generator/ConditionJpqlGenerator.java#L74) the selectedExpressions were not being copied to childContexts.
=> Fix KeyValueCollection multiple filters search

jmix-core/core/src/main/java/io/jmix/core/CoreConfiguration.java, jmix-rest/rest/src/main/java/io/jmix/rest/impl/RestParseUtils.java, jmix-rest/sample-rest/src/main/java/io/jmix/samples/rest/service/RestTestService.java, jmix-rest/sample-rest/src/main/java/io/jmix/samples/rest/service/RestTestServiceBean.java, jmix-rest/sample-rest/src/test/java/services/ServicesControllerFT.java, jmix-rest/sample-rest/src/test/resources/test_support/rest-services.xml, jmix-restds/restds/src/main/java/io/jmix/restds/RestDsConfiguration.java, jmix-restds/restds/src/main/java/io/jmix/restds/annotation/RemoteService.java, jmix-restds/restds/src/main/java/io/jmix/restds/impl/service/RemoteServiceBeanFactoryPostProcessor.java, jmix-restds/restds/src/main/java/io/jmix/restds/impl/service/RemoteServiceInvoker.java, jmix-restds/restds/src/main/java/io/jmix/restds/impl/service/RemoteServiceProxyFactoryBean.java, jmix-restds/restds/src/main/java/io/jmix/restds/impl/service/package-info.java, jmix-restds/restds/src/test/java/remote_service/RemoteServiceTest.java, jmix-restds/restds/src/test/java/test_support/service/CustomerService.java, jmix-restds/restds/src/test/java/test_support/service/SampleService.java, jmix-restds/restds/src/test/resources/logback-test.xml, jmix-restds/sample-rest-service/src/main/java/io/jmix/samples/restservice/app/CustomerService.java, jmix-restds/sample-rest-service/src/main/java/io/jmix/samples/restservice/app/SampleService.java
Introduced `@RemoteService` annotation to enable defining remote services. Added a proxy mechanism (`RemoteServiceProxyFactoryBean`) and bean processor (`RemoteServiceBeanFactoryPostProcessor`) to handle service instantiation and method calls. Included tests and updated configurations.
Definition on the server side:
```
@RestService("InventoryService")
public class InventoryService {
@RestMethod
public Double getAvailableInStock(Product product) {
return (double) Math.round(Math.random() * 100);
}
}
```
Definition on the client side:
```
@RemoteService(store = "products")
public interface InventoryService {
Double getAvailableInStock(Product product);
}
```
Invocation on the client side:
```
@Autowired
private InventoryService inventoryService;
@Subscribe(id = "availableBtn", subject = …
```
=> Annotated interfaces for calling REST services

jmix-authserver/authserver-starter/src/main/java/io/jmix/autoconfigure/authserver/AuthServerAutoConfiguration.java, jmix-authserver/authserver/src/main/java/io/jmix/authserver/AuthServerProperties.java
See https://github.com/jmix-framework/jmix/issues/2189
Additional filter chain with simple logout support (according to https://youtrack.haulmont.com/articles/PLAT-A-1518/Authorization-Server-logout).
- `jmix.authserver.post-logout-url-redirect-parameter-name` - name of url parameter from` /logout` request. This parameter should contain url to redirect after successful logout. 
Default: null (**should we add some default?**)
- `jmix.authserver.use-referer-post-logout` - allows to use `referer` header value as post logout redirect url. 
Propagate to `useReferer` parameter of `AbstractAuthenticationTargetUrlRequestHandler` that has the following order of redirect url determination: value from url parameter -> referer (if enabled) -> default (`/`), so it has less priority than url from …
=> Add logout support to auth server

jmix-messagetemplates/messagetemplates-starter/src/main/java/io/jmix/autoconfigure/messagetemplates/MessageTemplatesAutoConfiguration.java, jmix-messagetemplates/messagetemplates/src/main/java/io/jmix/messagetemplates/MessageTemplateConfigurer.java, jmix-messagetemplates/messagetemplates/src/main/java/io/jmix/messagetemplates/MessageTemplatesConfiguration.java, jmix-messagetemplates/messagetemplates/src/main/java/io/jmix/messagetemplates/impl/MessageTemplatesGeneratorImpl.java
See: #4334
Now you can override the default configuration by using the following code in your project:
```java
// ...
@Bean
public MessageTemplateConfigurer configuration(MessageTemplateProperties messageTemplateProperties,
FreeMarkerProperties freeMarkerProperties,
ObjectProvider<FreeMarkerVariablesCustomizer> variablesCustomizers) {
MessageTemplateConfigurer messageTemplateConfigurer =
new MessageTemplateConfigurer(messageTemplateProperties, freeMarkerProperties, variablesCustomizers);
// configurer changes
return messageTemplateConfigurer;
}
```
=> Use a bean for MessageTemplatesGeneratorImpl.defaultConfiguration jmix-framework/jmix#4334

jmix-appsettings/appsettings-flowui/src/main/java/io/jmix/appsettingsflowui/AppSettingsFlowUiConfiguration.java, jmix-appsettings/appsettings-flowui/src/main/java/io/jmix/appsettingsflowui/AppSettingsUiProperties.java, jmix-appsettings/appsettings-flowui/src/main/java/io/jmix/appsettingsflowui/view/appsettings/AppSettingsEntityView.java
Fixes: #671 
The UUID type has been removed from the skipping if condition in AppSettingsEntityView class
=> UUID fields are not generated in AppSettingsEntity editor screen #671

jmix-rest/rest/src/main/java/io/jmix/rest/impl/config/RestServicesConfiguration.java, jmix-rest/rest/src/main/java/io/jmix/rest/impl/openapi/OpenAPIGeneratorImpl.java
Fixes: #4474 
If httpMethod property in rest-services.xml is not set for controller method, both types of GET and POST requests will be processed simultaneously. They will be processed separately otherwise.
Added Nullable annotation for RestServicesConfiguration.getHttpMethod()
=> Open API detailed docs call produces NPE #4474

jmix-data/data/src/main/java/io/jmix/data/Sequences.java
=> Wrong value of sequences.createNextValue method in MS SQL DB #4500

jmix-restds/restds/restds.gradle, jmix-restds/restds/src/main/java/io/jmix/restds/impl/RestInvoker.java, jmix-restds/restds/src/test/java/rest_invoker/RestInvokerTracingTest.java, jmix-restds/restds/src/test/java/test_support/TestRestDsConfiguration.java, jmix-restds/sample-rest-service/src/main/java/io/jmix/samples/restservice/controller/TracingTestController.java
- Fix RestClient tracing integration by using injected RestClient.Builder instead of static factory method
- Add comprehensive integration test to verify W3C traceparent header propagation
- Implement TracingTestController as echo service for tracing verification
**Problem**: RestClient was not propagating tracing headers because it used `RestClient.builder()` static method, which doesn't include the configured ObservationRegistry.
**Solution**: Modified RestInvoker to inject `RestClient.Builder` bean from ApplicationContext (line 119), ensuring it gets the properly configured ObservationRegistry with
tracing handlers.
```java
// Before: Static factory method (no tracing)
RestClient.Builder builder = RestClient.builder();
// After: Injected bean with ObservationRegistry
RestClient.Builder …
```
=> Fix #4719 - Enable tracing propagation within restds module

jmix-data/data/src/main/java/io/jmix/data/Sequence.java
Added a way (equals and hashcode) to compare two objects of Sequence type
Issue - https://github.com/jmix-framework/jmix/issues/4660
Is a cherrypick for - https://github.com/jmix-framework/jmix/pull/2543
=> Equals and hashcode aren't defined in io.jmix.data.Sequence
